### ISSUE TITLE
addon no funciona en kodi 15.2(Git:02e7013) raspberry pi 2

### ISSUE THREAD

**Issue by upadrian** [ramiro/service.subtitles.subdivx#10]
Hola ramiro, te dejo el paste del problema.
El problema es con este sub http://www.subdivx.com/X6XNDQ0OTk2X-the-big-bang-theory-s09e05.html
Mismo problema con otros subs
Por cierto, la carpeta /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/ no existe
será por esto que no anda?

```
02:27:36  84.611694 T:1793061952   DEBUG: StartScript - calling plugin Subdivx.com('plugin://service.subtitles.subdivx/','7','?action=download&filename=https%3a%2f%2fr4---sn-hp57knls.googlevideo.com%2fvideoplayback%3fid%3dbdcf3595f11d347b%26itag%3d22%26source%3dwebdrive%26begin%3d0%26requiressl%3dyes%26mm%3d30%26mn%3dsn-hp57knls%26ms%3dnxu%26mv%3dm%26nh%3dIgpwcjAxLm1pYTA0KgkxMjcuMC4wLjE%26pl%3d20%26lmt%3d1445329981767984%26mime%3dvideo%2fmp4%26mt%3d1446603968%26ip%3d179.25.51.158%26ipbits%3d8%26expire%3d1446632840%26sparams%3dip%2cipbits%2cexpire%2cid%2citag%2csource%2crequiressl%2cmm%2cmn%2cms%2cmv%2cnh%2cpl%2clmt%2cmime%26signature%3d574B36C7379169C8C20007CB24C4DFBFFFD5E903.AC78B101B4262B2D759CE8B90FCDD21D7FE9CF24%26key%3dck2%26ir%3d1%26rr%3d12&id=X6XNDQ0OTY4X-the-big-bang-theory-s09e05')
02:27:36  84.612267 T:1419768896  NOTICE: Thread LanguageInvoker start, auto delete: false
02:27:36  84.612511 T:1793061952   DEBUG: WaitOnScriptResult - waiting on the Subdivx.com (id=10) plugin...
02:27:36  84.612625 T:1419768896    INFO: initializing python engine.
02:27:36  84.612732 T:1419768896   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/service.subtitles.subdivx/service.py): start processing
02:27:36  84.750687 T:1419768896  NOTICE: -->Python Interpreter Initialized<--
02:27:36  84.750999 T:1419768896   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/service.subtitles.subdivx/service.py): the source file to load is "/storage/.kodi/addons/service.subtitles.subdivx/service.py"
02:27:36  84.751457 T:1419768896   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/service.subtitles.subdivx/service.py): setting the Python path to /storage/.kodi/addons/service.subtitles.subdivx:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
02:27:36  84.751595 T:1419768896   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/service.subtitles.subdivx/service.py): entering source directory /storage/.kodi/addons/service.subtitles.subdivx
02:27:36  84.751816 T:1419768896   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/service.subtitles.subdivx/service.py): instantiating addon using automatically obtained id of "service.subtitles.subdivx" dependent on version 2.14.0 of the xbmc.python api
02:27:36  84.947899 T:1419768896    INFO: SUBDIVX - Version: 0.0.8 -- Action: download
02:27:36  84.948540 T:1419768896   DEBUG: SUBDIVX - debug_dump_path: xbmc.translatePath(__addon__.getAddonInfo('profile')) (<type 'str'>): /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/
02:27:36  84.948822 T:1419768896   DEBUG: SUBDIVX - debug_dump_path: __profile__ (<type 'unicode'>): /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/
02:27:36  84.952255 T:1419768896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp66s65z'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.subdivx/service.py", line 548, in <module>
                                                main()
                                              File "/storage/.kodi/addons/service.subtitles.subdivx/service.py", line 526, in main
                                                workdir = tempfile.mkdtemp(dir=__profile__)
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-RPi2.arm-6.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/tempfile.py", line 325, in mkdtemp
                                            OSError: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp66s65z'
                                            -->End of Python script error report<--
02:27:36  84.963821 T:1968365568   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
02:27:36  85.039215 T:1419768896    INFO: Python script stopped
02:27:36  85.039474 T:1419768896   DEBUG: Thread LanguageInvoker 1419768896 terminating
02:27:36  85.055046 T:1793061952   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
02:27:36  85.055382 T:1793061952   ERROR: GetDirectory - Error getting plugin://service.subtitles.subdivx/?action=download&filename=https%3a%2f%2fr4---sn-hp57knls.googlevideo.com%2fvideoplayback%3fid%3dbdcf3595f11d347b%26itag%3d22%26source%3dwebdrive%26begin%3d0%26requiressl%3dyes%26mm%3d30%26mn%3dsn-hp57knls%26ms%3dnxu%26mv%3dm%26nh%3dIgpwcjAxLm1pYTA0KgkxMjcuMC4wLjE%26pl%3d20%26lmt%3d1445329981767984%26mime%3dvideo%2fmp4%26mt%3d1446603968%26ip%3d179.25.51.158%26ipbits%3d8%26expire%3d1446632840%26sparams%3dip%2cipbits%2cexpire%2cid%2citag%2csource%2crequiressl%2cmm%2cmn%2cms%2cmv%2cnh%2cpl%2clmt%2cmime%26signature%3d574B36C7379169C8C20007CB24C4DFBFFFD5E903.AC78B101B4262B2D759CE8B90FCDD21D7FE9CF24%26key%3dck2%26ir%3d1%26rr%3d12&id=X6XNDQ0OTY4X-the-big-bang-theory-s09e05
02:27:36  85.089539 T:1574954048   DEBUG: webserver: request received for /jsonrpc
```

**Comment by upadrian** [comment]
Ramiro, se me dió por crear la carpeta a mano, /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/ y resulta que ahora si anda.

Te cuento que el sistema lo instalé hace poco, de 0 sin modificaciones.
Usé el noobs y después actualizó solo. Uso el Genesis, y tu plugin lo instalé del repositorio oficial. Ah y tambien puse el Addon instaler.
slds!

**Comment by ramiro** [comment]
@upadrian 

¡Gracias por el reporte detallado!

En 0.0.8 comenzamos a usar ese directorio `service.subtitles.subdivx/` en `userdata/addon_data/` pero aparentemeente  asumimos erroneamente que XBMC/Kodi lo creaba por nosotros.

Lo crea si es que uno toca al menos una vez el setting del addon.

Te voy a pedir que si podes me ayudes a probar lo que va a ser la versión 0.1.0 con tu Kodi 15.x en Raspi:

De la siguiente manera: 
- Borrar ese directorio con todo su contenido
- Descargar `service.py` de este repositorio: https://raw.githubusercontent.com/ramiro/service.subtitles.subdivx/master/service.py y reemplazando el que ya existe en `addons/service.subtitles.subdivx/`
- Probar el addon nuevamente

Yo voy a probar lo mismo en un par de instalaciones de XBMC/Kodi mas viejas en otras plataformas.

**Comment by upadrian** [comment]
Esta noche te lo mando!

**Comment by ramiro** [comment]
Genial @upadrian 

Olvidé comentarte dos cosas:
- La lista de cambios es esta:
  https://github.com/ramiro/service.subtitles.subdivx/blob/a5a4dc93bd8b58750e1d25d94b1c4bcaede59fc6/changelog.txt#L1-L7
- Si podes probarlo exaustivamente mucho mejor!

**Comment by upadrian** [comment]
Ramiro, ayer lo estuve probando y anduvo bárbaro.
Borré la carpeta y me puse a ver The Andrómeda Strain(2008) y 0 problema.
Ahora, tengo un feature request para pasarte, lo pongo como nuevo issue?

**Comment by ramiro** [comment]
Adiran,

Si. Dale nomas, como nuevo issue.

Muchas gracias por la ayuda, yo también probé y no experimenté problemas.

Veo si hoy etiqueto el estado actual como versión 0.1.0. No quisiera hacer
esperar mas a los usuarios si es que se les estan presentando problemas.

Vamos a comenzar a trabajar asi:

Las versiones 0.n.0 (0.1.0, 0.2.0, ...) van a ser las oficiales que
publicamos en el repositorio de addons de Kodi.

Las versiones 0.n.m (0.1.1, 0.1.2, 0.1.3, ...) van a ser versiones para
prueba de arreglos en la version anterior (0.1.0 en el ejemplo) o con
features nuevos y son previas a la 0.n+1 (0.2.0 en el ejemplo).

De esta manera va a ser fácil que un usuario pueda identificar y repotrar
cuál es la vesión que está usando e el caso de que encuentre un problema.

Si podes ayudarme en todo esto seria genial. Sobre todo porque tenes una
plataforma que yo no tengo y porque aparentemrnte sos de ver series que es
algo que yo no hago.

¡Abrazo!

On Thu, Nov 5, 2015 at 10:00 AM, Adrián Suárez notifications@github.com
wrote:

> Ramiro, ayer lo estuve probando y anduvo bárbaro.
> Borré la carpeta y me puse a ver The Andrómeda Strain(2008) y 0 problema.
> Ahora, tengo un feature request para pasarte, lo pongo como nuevo issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ramiro/service.subtitles.subdivx/issues/10#issuecomment-154053171
> .

## 

Ramiro Morales
@ramiromorales

**Comment by upadrian** [comment]
Claro hermano!
Python no es lo mío, pero algo pude entender y meter mano. Soy del palo php :D
Por otro lado, si, lo que más hago es mirar series. Ya había hecho un parche "a lo bruto" cuando subdivx metió la página intermedia para poder descargar subtitulos.

Ya te hago el issue con el feature request.
slds!

**Comment by ramiro** [comment]
Cerramos porque este issue particular está solucionado en la v0.1.0
