### ISSUE TITLE
Previsualizar cadena de búsqueda

### ISSUE THREAD

**Issue by upadrian** [ramiro/service.subtitles.subdivx#11]
Esto es un feature request.
Muchas veces pasa que los plugins no encuentran subtitulos, y a veces es porque no estan buscando correctamente quizás porque el titulo es incorrecto.
Ejemplo, miniserie The andrómeda Strain(2008). El plugin no encuentra subs, hasta que buscas a mano el titulo.
Creo que estaría bueno VER que búsca, quizás al abrir "buscar manualmente" que te precargue la cadena de bùsqueda. Así no es necesario reescribir todo el titulo, sino corregir.

**Comment by ramiro** [comment]
@upadrian 

Cuando vi este issue pensé que era una buena idea y también que era algo implementable.

Pero ahora que intento trabajar en el mismo, veo que un addon no tiene los medio para lograr ninguna de las dos cosas que sugeris, a saber:
- Tener control de la UI como para poder mostrarle al usuario cuál es la cadena que se está buscando en subdivx.com
- Tener control sobre lo que aparece en la caja en la cual el usuario tipea la cadena a buscar en el caso de búsqueda manual.

Esto es asi porque en realidad el addon es completamente pasivo. Solo es invocado por Kodi/XBMC ante eventos del usuario o del mismo Kodi:
- Primero es llamado con el nombre del archivo de video, momento en el que tiene que devolver a Kodi la lista de lo que encontró en subdivx.com
- Y luego es llamado con el item que el usuario eligio de esa lista (si es que el usuario eligió algo) para proceder a la descarga de ese subtitulo. 

Si se te ocurre alguna manera de implementar esto avisame. De otra forma creo que no nos va a quedar otra que cerrar este issue.

**Comment by upadrian** [comment]
Lamento que recién veo esto... y estamos en Octubre!
Dejé un poco de lado el Kodi, solo recientemente me puse a usarlo.

Mi planteeo sigue igual, pero veo que según tu respuesta, de momento no se puede.

We stay in touch!
