### ISSUE TITLE
Error al descargar subtitulo version 0.1.0

### ISSUE THREAD

**Issue by juanredondo** [ramiro/service.subtitles.subdivx#13]
Ramiro,
Me muestra este error el log al intentar descargar un subtitulo de la serie Humans:

23:24:39 1077.372314 T:1186985024   DEBUG: xbmc.translatePath(**addon**.getAddonInfo('profile')) (<type 'str'>): /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/
23:24:39 1077.372559 T:1186985024   DEBUG: **profile** (<type 'unicode'>): /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/
23:24:39 1077.374390 T:1186985024   DEBUG: workdir (<type 'unicode'>): /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpYGPB6U/
23:24:39 1077.375366 T:1186985024   DEBUG: SUBDIVX - get_url: Fetching http://www.subdivx.com/X6XNDM3MTMxX-humans-s01e02
23:24:40 1077.739014 T:1186985024   FATAL: SUBDIVX - Download: Expected content not found in selected subtitle intermediate detail page
23:24:40 1077.739380 T:1459614784   DEBUG: WaitOnScriptResult- plugin returned successfully
23:24:40 1077.764038 T:1967968256   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
23:24:43 1080.754517 T:1186985024   DEBUG: SUBDIVX - _double_dot_fix_hack: video_filename = /media/sda1-ata-WDC_WD10EADS-00L/Series/Humans/Season 01/Humans.S01E02.REPACK.1080p.WEB-DL.DD5.1.H.264-NTb.mkv
23:24:43 1080.756104 T:1186985024   DEBUG: SUBDIVX - _double_dot_fix_hack: work_path = /media/sda1-ata-WDC_WD10EADS-00L/Series/Humans/Season 01/Humans.S01E02.REPACK.1080p.WEB-DL.DD5.1.H.264-NTb.mkv
2

Me ha aprecido nuevo al acualizar a la 0.1.0, anteriormente, en la 0.8, me mostraba el error de descarga reportado de los archivos temporales.

**Comment by upadrian** [comment]
Ramiro!
Sacaron la pantalla intermedia, ahora baja directamente.
Ejemplo: http://www.subdivx.com/X6XMjc5NDA8X-after-the-thin-man-1936.html

Van y vienen, terribles crá!

**Comment by upadrian** [comment]
Ramiro, dejo aqui el código funcionando. Comenté lo referente a la página intermedia.
http://pastebin.com/JazVdRXf
