### ISSUE TITLE
Problema al bajar subtitulos en Kodi desde Amazon FireTV Stick

### ISSUE THREAD

**Issue by Jadeka** [ramiro/service.subtitles.subdivx#15]
Buen día:

Hace ya tiempo que uso el addon de Subdivx y no he tenido problema sin embargo de un tiempo para acá he notado que cuando busco subtitulos en español y me salen en la lista algunos cuyo nombre dicen provenir de Tusubtitulo.com el addon me vota un error y no lo puedo descargar

Esto solo me ocurre al usar el addon en mi Amazon FireTv stick con kodi 16.1 Jarvis porque al intentarlo desde mi pc de escritorio funciona perfecto.

No se si es la mejor manera de comunicarme con uds y la verdad no tengo mucha experiencia en estas cosas, pero si me pueden ayudar estaría muy agradecido, adjunto archivo kodi.log por si sirve de algo.

Gracias por su trabajo y dedicación

[kodi.log.txt](https://github.com/ramiro/service.subtitles.subdivx/files/275616/kodi.log.txt)

**Comment by IvanRF** [comment]
@Jadeka este error se solucionó en e8f0fe0. Espera a que salga la versión 0.2.5 o descarga el zip actual de github
