### ISSUE TITLE
Error Downloading Subtitles

### ISSUE THREAD

**Issue by ldimitroff** [ramiro/service.subtitles.subdivx#16]
I'm trying to download subtitles from kodi on openelec and seems that there is an issue with the script.

Followed this solution with no luck http://forum.kodi.tv/showthread.php?tid=195374

This is what the folder contains: 

> LucasPi:~/.kodi/userdata/addon_data/service.subtitles.subdivx # ls
> settings.xml  tmp3sIjuO     tmp8bXAnZ     tmpDbNZpe     tmpHNlTjY     tmpNiddOV     tmpSgKkCm     tmpY8cEmE     tmpahc50a     tmpkSN4I2     tmpripKIn     tmpvMfcWC
> temp          tmp40yqiQ     tmp9as_PV     tmpDqgK3j     tmpHisyhP     tmpO0JB1q     tmpTKlNmw     tmpY_ud6J     tmpcicwRK     tmplQWD07     tmpsDRpG0     tmpwI7NcT
> tmp2XWHW3     tmp4HYO2n     tmpANXTWf     tmpE4HkjT     tmpI9YMNZ     tmpO35hVQ     tmpUdhqD7     tmpZ9JBCD     tmpcmx8dO     tmpm_koS_     tmpsJtneF     tmpwRrFdW
> tmp2dpmsC     tmp6K9r3T     tmpATZgSF     tmpEihtX3     tmpJCG8U_     tmpPyNBjB     tmpV_cDZP     tmpZb8Ew3     tmpd158wX     tmpmaSjNp     tmpspr9Jv     tmpwprp_K
> tmp31lb6k     tmp6UU4jd     tmpBJM_8T     tmpFVu_ah     tmpLYz2dt     tmpRH83tG     tmpVvQ_d8     tmpZbjaMP     tmpezRTJR     tmpoW9ZCb     tmpt0CH0o     tmpyWwfSi
> tmp3SSwqE     tmp7M_MzL     tmpBwliqN     tmpG8Yl3D     tmpMDabP9     tmpRJ1dEc     tmpXWM4yN     tmp_PQgSh     tmpgXbpf0     tmpolr5Ym     tmptcxmvM     tmpz6oc6F
> tmp3inAlu     tmp8TXNnx     tmpCpl_Ox     tmpGxIUgt     tmpMKA54E     tmpS814py     tmpXeesju     tmpaLqbCo     tmpk0nvBW     tmppVNxWG     tmpv92XPn     tmpzLi1du
> LucasPi:~/.kodi/userdata/addon_data/service.subtitles.subdivx # cd temp/
> LucasPi:~/.kodi/userdata/addon_data/service.subtitles.subdivx/temp # ls
> LucasPi:~/.kodi/userdata/addon_data/service.subtitles.subdivx/temp #

**Comment by ramiro** [comment]
@ldimitroff ¡Hola! Podrias hacernos el favor de intentar reproducir este problema que experimentabas con la nueva versión 0.2.5 que está disponible a partir de hoy que debería instalarse automáticamente.  Y luego reportarnos si sigue ocurriendo.

Muchas gracias.

**Comment by ldimitroff** [comment]
@ramiro Hola! Lo testeo y les doy el feedback, ultimamente no he tenido problemas en descargar subtitulos, solamente hay veces que me da resultados y falla la descarga. 
Muchas gracias por atacar mi problema

**Comment by ramiro** [comment]
@ldimitroff ¡Hola Lucas! ¿Seguis usando Kodi? ¿Este add-on? ¿Se ha solucionado este problema que experimentabas?

**Comment by ldimitroff** [comment]
Hola @ramiro !! Sigo usando Kodi y utilizo este add-on. (pido disculpas ya que veo que nunca conteste en este thread que se habia solucionado) Actualmente es el unico add-on que uso, anda perfecto!

**Comment by ramiro** [comment]
¡Gracias!
