### ISSUE TITLE
Error al bajar subtitulos con un archivo txt y un srt

### ISSUE THREAD

**Issue by pechex** [ramiro/service.subtitles.subdivx#17]
Por ejemplo este: http://www.subdivx.com/X6XNDgyNzY5X-the-walking-dead-s07e02.html
Y todos los de substeam son iguales.

Ademas del SRT el zip contiene un TXT con instrucciones. Da el siguiente error al intentar descargar:
00:03:44 4590.503418 T:1266676720  NOTICE: SUBDIVX - Version: 0.2.4 -- Action: search
00:03:50 4596.712891 T:1266676720  NOTICE: SUBDIVX - Version: 0.2.4 -- Action: download
00:03:51 4597.465332 T:1266676720 WARNING: SUBDIVX - Download: Intermediate detail page for selected subtitle or expected content not found. Handling it as final download page
00:03:55 4601.451172 T:1266676720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xa2' in position 101: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py", line 587, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py", line 569, in main
                                                subs = Download(params["id"], workdir)
                                              File "/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py", line 431, in Download
                                                saved_fname = _save_subtitles(workdir, content)
                                              File "/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py", line 389, in _save_subtitles
                                                rval, fname = _handle_compressed_subs(workdir, tmp_fname)
                                              File "/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py", line 345, in _handle_compressed_subs
                                                if _wait_for_extract(workdir, filecount, base_mtime, MAX_UNZIP_WAIT):
                                              File "/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py", line 315, in _wait_for_extract
                                                mtime = os.stat(pjoin(workdir, fname)).st_mtime
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xa2' in position 101: ordinal not in range(128)
                                            -->End of Python script error report<--
00:03:55 4601.869141 T:1317008368   ERROR: GetDirectory - Error getting plugin://service.subtitles.subdivx/?action=download&filename=nfs%3a%2f%2f192.168.1.100%2fexport%2fTV%2fThe%20Walking%20Dead%2fThe.Walking.Dead.S07E02.720p.HDTV.x264-AVS%5brarbg%5d%2fThe.Walking.Dead.S07E02.720p.HDTV.x264-AVS.mkv&id=X6XNDgyNzY5X-the-walking-dead-s07e02

Probando se me ocurrio eliminar TXT de la lista de extensiones de subtitulos validos y empezo a funcionar lo mas bien. 
En la linea 56 modifique 
SUB_EXTS = ['srt', 'sub', 'txt'] 
por 
SUB_EXTS = ['srt', 'sub'] 

 y funciona lo mas bien.

Espero se haya entendido

**Comment by ramiro** [comment]
Se entiende, Gracias por tomarte el trabajo de reportar.

No puedo reproducir esto. Me baja ese subs sin poblemas.

Creo que está relacionado con el caracter extraño que hay en el filename del .txt (la letra "o" que deberia ser acentuada en `'utilización'` pero que a mi en Linux+ext4 me muestra otro chirimbolo cuando lo veo como UTF-8)

También creo que hay dos posibles causas:

1. El orden en el que me está enumerando el contenido del .zip a mi es distinto al que usa en tu caso. A vos primero el .txt y revienta, a mi primero el .srt
2. El hecho de que aparentemente tenes tus downloads en un share NFS. Pregunta: ¿Donde tenes el dir temporario en el cual kodi+el plugin bajan y descomprimen cosas? en mi caso es ~/.kodi/temp/

**Comment by pechex** [comment]
Es correcto, tengo un share NFS con los archivos y los KODI estan en 2 Raspberry PI 2 usando OSMC. El directorio TEMP es el default, ~/.kodi/temp.

El error parece ser algo del encoding como vos decis: Error Contents: 'ascii' codec can't encode character u'\xa2' in position 101: ordinal not in range(128)

El caracter seria este creo: https://vazor.com/unicode/c00A2.html

**Comment by ramiro** [comment]
¿Qu'e sistema de archivos tenes en el server NSF y en los Raspi?

¿NFS tiene alguna opción al publicar o montar un share que permita especificar el encoding de los paths?

¿Qué sucede si queres copiar manualmente ese .txt al directorio donde tenes el episodio de la serie? ¿Se copia correctamente?

**Comment by ramiro** [comment]
This got fixed by
 
a) Changes proposed by @IvanRF in #19 and incorporated in e8f0fe04cc656c8f00d125014e5dbffa6f7d083c
b) 890e3d423fd450ed03ef9a5cfc70f031d707dc63

And will be released with v0.2.5.
