### ISSUE TITLE
Extract performance

### ISSUE THREAD

**Issue by IvanRF** [ramiro/service.subtitles.subdivx#20]
Por lo que ví, la parte de la extracción de archivos es código heredado y tiene muchos `time.sleep()` que no son necesarios.
De [Using Built-in Functions from python](http://kodi.wiki/view/Built-in_scripting#Using_Built-in_Functions_from_python)

> On 28.11.2011 a optional parameter was added. Normal call will be non-blocking - so it returns before the extraction has been finished. Now it's possible to call built-in functions blocking by doing:
 `xbmc.executebuiltin('XBMC.RunScript(Q:\Scripts\myscript.py)', True)`

Es decir, con sólo agregar el `True` no es necesario todo ese código que se queda esperando a la extracción (encima es la causa de issues previos).

Extra: [service.subtitles.subscene](https://github.com/manacker/service.subtitles.subscene/blob/master/service.py#L434) lo hace así.

**Comment by IvanRF** [comment]
contento que actualizaste pero una lástima que no usaste mi Pull request. De la forma que aplicaste los cambios no queda rastro de mi usuario como `contributor`

**Comment by IvanRF** [comment]
@ramiro contento que actualizaste pero una lástima que no usaste mi Pull request. De la forma que aplicaste los cambios no queda rastro de mi usuario como contributor

**Comment by ramiro** [comment]
@IvanRF 
¡Mil disculpas, esa no era la intención!

El problema con el pull request #19 es que el mismo había arreglos para mas de un issue. Lo ideal hubiese sido un PR por issue (y en lo posible cada uno de ellos limpio sin idas y vueltas pero esto no es tan importante) de manera que se puede a) trabajar haciendo reviews y pidiendo modificaciones al autor b) realizar merges (posiblemente luego de las revisiones) en cada uno de ellos.

Por otra parte no se usó exactamente el mismo código propuesto.

Sin embargo se te han dado créditos en todos los cambios en los que colaboraste de una forma u otra. Tanto en los commit messages como en el changelog. De manera que no es completamente correcto eso de que no quedan rastros de tus contribuciones.

**Comment by IvanRF** [comment]
@ramiro sólo me refería en github ([link](https://github.com/ramiro/service.subtitles.subdivx/graphs/contributors)), pero no hay drama. Sí, lo otro lo ví 👍 . Gracias por mantener el addon!
