### ISSUE TITLE
Error bajando subtitulos

### ISSUE THREAD

**Issue by juanredondo** [ramiro/service.subtitles.subdivx#22]
No me baja subtitulos en kodi 17 rc. En grneral no me ha funcionado ninguno. Pero ahora mismo el que tengo es homeland.s0601.amzn.webrip.dd5.1.x264-ntb.mkv

**Comment by ramiro** [comment]
@juanredondo Neceistariamos mas datos.

¿Te muestra un mensaje de error?

¿No genera errorpero no encuentra nungún subtítulo? 

¿Ves en subdivx.com que si hay subtítulos pero el addon no los muestra?

¿Qué versión del addon estás usando?

¿Yo he estado usando la version 0.2.4 y la WIP 0.2.5 en Kodi v17 rc3 sin problemas.

**Comment by juanredondo** [comment]
Kodi v17 rc3
Version addon "cramm - 0.2.4" 
Lista los subtitulos bien pero al descargar sale popup de error: Fallo al descargar el subtitulo.
No ocurre con todos. En el archico q te he puesto antes ocurre con una version web-rip de MarcusL

Si necesitas el log te lo puedo mandar

**Comment by IvanRF** [comment]
@juanredondo descarga el zip de la versión actual en github, instala el addon desde ese zip y probá si podes descargar el subtítulo

**Comment by juanredondo** [comment]
Funcionando perfectamente. Perdona por laa molestias te cierro la incidencia
