### ISSUE TITLE
Traducción de descripción a español en addon.xml

### ISSUE THREAD

**Issue by ramiro** [ramiro/service.subtitles.subdivx#25]
Aparentemente es posible incluir la descripción en mas de un idioma. Actualmente la misma está en inglés.

**Comment by IvanRF** [comment]
Tal vez por el público al que está dirigido el addon sólo debería estar en español, no tiene mucho sentido mantener la lista de cambios en dos idiomas.

**Comment by ramiro** [comment]
Es cierto lo que comentas sobre el idioma de las entradas del change log, tenemos que ver que hacemos al respecto y a lo mejor atacarlo cuando se trabaje en #24.
Pero en este caso yo me referia al summary y la description (¿y algún otro?):
- https://github.com/ramiro/service.subtitles.subdivx/blob/95ade80ecad45d4b0d6dceae92c90591655bf810/addon.xml#L13-L14
- http://kodi.wiki/view/addon.xml#.3Csummary.3E
