### ISSUE TITLE
Eliminar los directorios temporales creados por el addon

### ISSUE THREAD

**Issue by ramiro** [ramiro/service.subtitles.subdivx#29]
El addon crea un directorio temporal usando `tempfile.mkdtemp()` de la stdlib Python con cada descarga de subtítulo.

Esto se introdujo en 3c90853c793f6847e2d6f9e2867147661e66d2cb.

Por una parte, facilita mucho las cosas porque cada intento de descarga de un subtítulo trabaja sobre un directorio 'limpio', ej. el bugfix de @IvanRF en https://github.com/ramiro/service.subtitles.subdivx/pull/19/commits/79937dc65f29898d726d7d3f5ec21b1ee0ad321f (committed in e8f0fe04cc656c8f00d125014e5dbffa6f7d083c)

Pero por otra parte pueden acumularse muchos directorios. Ejemplo de un sistema Linux:
```
$ find ~/.kodi/userdata/addon_data/service.subtitles.subdivx -maxdepth 1 -type d | wc -l
188
```

```
$ du -sch ~/.kodi/userdata/addon_data/service.subtitles.subdivx
28M ~/.kodi/userdata/addon_data/service.subtitles.subdivx
28M	total
```

Tendriamos que ver si es posible volver a intentar borrar ese directorio de una forma robusta (o sea que no genere errores en el addon aun cuando no es posible eliminiar el directorio total o parcialmente) aunque sea 'best effort'.

**Comment by IvanRF** [comment]
Sí, esto lo ví también cuando hice pruebas en Android, tenía más de 80 carpetas.

Cuando el subtítulo se pasa a Kodi ya se libera el recurso o Kodi lo lee desde el archivo descargado?

**Comment by ramiro** [comment]
Algo que olvidé mencionar es que esto por ahi no es un problema en un media center con PC y HDD en Linux o Windows. El problema puede darse en un mediaplayer tipo Android set top box o stick en los cuales el espacio de almacenamiento es escaso.

**Comment by ramiro** [comment]
> Cuando el subtítulo se pasa a Kodi ya se libera el recurso o Kodi lo lee desde el archivo descargado?

Cuando se le pasa el archivo a Kodi este lo copia a su lugar definitivo con el nombre cambiado y lo que nosotros descargamos/descomprimimos no se usa mas.
