### ISSUE TITLE
Incluir TXT como posible extensión de subtítulos

### ISSUE THREAD

**Issue by dareste** [ramiro/service.subtitles.subdivx#32]
Este subtítulo, una vez descomprimido

http://www.subdivx.com/X6XNDgwMjA3X-brooklyn-ninenine-s04e03

resulta en el nombre

Brooklyn.Nine-Nine.S04E03.720p.HDTV.x264-AVS[PRiME].txt

lo cual hace que la función _handle_compressed_subs falle:

```
00:38:19.814 T:139995646228224   DEBUG: SUBDIVX - get_url: Fetching http://www.subdivx.com/X6XNDgwMjA3X-brooklyn-ninenine-s04e03
00:38:20.145 T:139995646228224 WARNING: SUBDIVX - Download: Intermediate detail page for selected subtitle or expected content not found. Handling it as final download page
00:38:20.146 T:139995646228224   DEBUG: SUBDIVX - get_url: Fetching http://www.subdivx.com/bajar.php?id=480207&u=8
00:38:20.740 T:139995646228224   DEBUG: SUBDIVX - _save_subtitles: Saving subtitles to '/home/xxxxx/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpQ2thx3/subdivx.rar'
00:38:20.761 T:139995646228224  SEVERE: SUBDIVX - _handle_compressed_subs: Failed to unpack subtitles
```

La razón es que no se contempla .txt como posible extensión del subtítulo. El siguiente cambio en la línea 59:

```
- SUB_EXTS = ['SRT', 'SUB', 'SSA']
+ SUB_EXTS = ['SRT', 'SUB', 'SSA','TXT']
```

parece solucionar el problema.

**Comment by ramiro** [comment]
En versiones previas ya estaba incluido .txt.

Pero traía mas problemas que ventajas. Se sacó en 890e3d423fd450ed03ef9a5cfc70f031d707dc63 (antes del release de la versión actual).

Lamentablemente hay cuestiones de falta calidad de los subtítulos (como esta de que tenga extensión .txt) que no vamos a poder manejar con soluciones simples.  A lo mejor en el futuro podemos implementar algo mas robusto: Por ejemplo algún heurístico que "mire dentro" de los archivos y detecte si realmente son subs con formato SubRip.

**Comment by dareste** [comment]
Entiendo. Gracias!
