### ISSUE TITLE
Error al descargar subtitulos en Kodi 17.5

### ISSUE THREAD

**Issue by cacafuti8888** [ramiro/service.subtitles.subdivx#34]
Pues como dice el titulo, desde hace unos dias da error al descargar los subtitulos, estoy en Raspberry Pi 3 con OSMC version 2017.10-1. Desconozco si sucede desde la actualizacion pero si te puedo decir que fue cerca.

Gracias en adelante

**Comment by delima45** [comment]
For several days now the subtitles of Subdivx have not been downloaded in Kodi. I use a TVBOX MXQ Pro.
Thanks

**Comment by Lanzheim** [comment]
It seems to be a problem with the subdivx addon. It finds subtitles but it is not possible to download them, it will always prompt an error, like "can't download subtitle". I'm on kodi 17.5 pc version and 17.6 android and in both platforms the problem is present.

**Comment by TomiMc** [comment]
Me pasa lo mismo, mirando el codigo, parece ser que algo han cambiado en la web de subdivx.com y a la hora de parsear cierta informacion falla.
He encontrado lo que han cambiado, el fix es muy facil. En el fichero service.py en la linea nº 91
cambiar
<b>**Bajar**</b></a>',
por:
<b>**Download**</b></a>',

y ya vuelve a descargar ok.

**Comment by matteraf** [comment]
Hola, este es el error

(se puede ver en .kodi/temp/kodi.log)

23:38:02.246 T:1453319152 NOTICE: SUBDIVX - Version: 0.2.5 Action: download
23:38:03.949 T:1453319152 WARNING: SUBDIVX - Download: Intermediate detail page for selected subtitle or expected content not found. Handling it as final download page
23:38:03.952 T:1453319152 FATAL: SUBDIVX - Download: Expected content not found in final download page

Y para mi es porque algo cambió en la página, creo que ahora para bajar el subtitulo es necesario autenticarse mientras antes no era necesario.  No le echen la culpa al addon sino a los genios de la página que hacen cambios arbitrarios sin avisar.

**Comment by matteraf** [comment]
OK, probemos esto

````
$ diff service.py service.py.ori
91c91
< DETAIL_PAGE_LINK_RE = re.compile(r'<a rel="nofollow" class="detalle_link" href="http://www.subdivx.com/(?P<id>.*?)"><b>Download</b></a>',
---
> DETAIL_PAGE_LINK_RE = re.compile(r'<a rel="nofollow" class="detalle_link" href="http://www.subdivx.com/(?P<id>.*?)"><b>Bajar</b></a>',
````

en mi raspi3 el file está en 

/home/osmc/.kodi/addons/service.subtitles.subdivx/service.py

**Comment by juancaar** [comment]
Puedo confirmar que el cambio que nos sugiere @TomiMc y @matteraf  funciona a la perfeccion. 

Esta falla justo ocurrio cuando pase mi Pi3 de retropie a libreelec y pense que habia sido un probelma durante el cambio. 

Gracias por la ayuda. Esperamos una version 0.26 para los que no saben como moverse en un sistema linux.

**Comment by cacafuti8888** [comment]
Matteraf nadie le ha echado la culpa al addon, simplemente creo que es más fácil adaptar el addon a los cambios de la web que al revés, aunque quizá me equivoque.

Luego pruebo el "parche" a ver si a mi tb me funciona. Saludos

**Comment by matteraf** [comment]
cacafuti8888 si sabes leer inglés vas a apreciar que le endilgan la culpa al addon.
Ya que otro amigo se tomó el trabajo de revisar el código y proponer el cambio que dicho sea de paso, es una estupidez, te pido por favor que no te pongas en la cómoda posición de que los demás te resulevan los problemas.  Demasiado que uno lo encontró y lo solucionó.  Y funciona.  Garantizado.

**Comment by cacafuti8888** [comment]
Yo no tengo conocimientos de código, como mucho puedo aplicar los cambios que habéis sugerido. Me guste o no dependo de gente con conocimientos como vosotros para identificar y solventar el problema, simplemente me he limitado a abrir este foro. Eso sí, como bien he comentado antes creo que con independencia de lo que realmente haya sucedido para que el addon diese error al descargar subtitulo, el problema está intrínsecamente en el addon, porque es el addon el que se adapta a la web, no la web al addon, eso es lo que yo creo, y como te dije antes puedo estar equivocado. Mi intención no es faltar a nadie, simplemente ayudar en lo que mis limitados conocimientos puedan ayudar, pero si alguien se ha molestado con algo pues pido disculpas sinceramente y agradezco el tiempo que han dedicado. Saludos

**Comment by ramiro** [comment]
Estimados,

No nos peleemos.

Recordemos que este addon no es un software oficial ni relacionado de manera alguna con subdivx.com.  Cada cambio en el diseño y el funcionamiento en el sitio subdivx.com usualmente ocasiona que tengamos que actualizar el código del addon. Esto ha sido así, lo es ahora y va a  ser.

Pero los dueños del sitio no tienen ninguna obligación para con nosotros. Ni nosotros estamos en posición de exigirles nada. Mas bien debemos agradecerles haber creado una comunidad en la cual se encuentran subtítulos de excelente calidad. La mejor del idioma castellano, en mi humilde opinión.

Espero poder actualizar el addon este fin de semana con los cambios propuestos. Efectivamente será una versión 0.2.6

**Comment by ramiro** [comment]
¿Alguien puede pegar un enlace a un subtítulo en subdivx.com de ejemplo en el cual les falle la descarga debido a este problema?

**Comment by juancaar** [comment]
Este me estaba fallando(y todos los otros) pero probe con este despues del cambio que nos dieron y funciono. 

https://www.subdivx.com/X6XNTE4MTUxX-the-middle-s09e05.html

**Comment by matteraf** [comment]
Ramiro, falla en todos, y el fix de TomiMc lo resuelve.

**Comment by matteraf** [comment]
Ramiro, no es un tema de pelea, simplemente porque se como es la cosa, que esto es un software libre, que se hace a pulmón, lo mínimo que se le puede pedir a los usuarios es un poco de respeto.
Respecto a quien es el responsable de la falla es depende como lo mires, podemos decir que la página fue por cambiar a su antojo el contenido o bien podemos decir que es del addon por no adecuarlo a la página, son puntos de vista como los gustos por los ciolores que cada uno tenga.

**Comment by cacafuti8888** [comment]
Acabo de cambiar en la línea 91 'Bajar' por 'Download' he desactivado y vuelto a activar el addon y me sigue saliendo el error, desconozco que he hecho mal.

El subtitulo que estoy intentando descargar es 

https://www.subdivx.com/X6XNTE4NjQ1X-supernatural-s13e05.html

De todas formas mi línea 91 es diferente (o me sale diferente)

> `DETAIL_PAGE_LINK_RE`` = re.compile(r'<a rel="nofollow" class="detalle_link" href="http://www.subdivx.com/(?P<id>.*?)"><b>Download</b></a>',`

**Comment by matteraf** [comment]
Bajatelo de acá, reemplaza lo que tengas (hace copia de service.py por las dudas) por esto:

https://pastebin.com/WgtAd8Yg

**Comment by Lanzheim** [comment]
Acabo de realizar el cambio y tampoco me funcionó.

Estoy tratando de descargar cualquiera de los subtitulitos de Rick and morty s03e09

**Comment by cacafuti8888** [comment]
No me funciona el cambio, sigue dando error al descargar, sea el subtitulo que sea.

**Comment by Lanzheim** [comment]
En unos minutos intentaré con el archivo de @matteraf

**Comment by Lanzheim** [comment]
Remplacé mi service.py con el de @matteraf y sigue sin funcionar.

**Comment by juancaar** [comment]
Les comento que antes me funciono y ahora dejo de funcionar... Los que les funciono vuelvan a intentar a ver si les pasa igual.

**Comment by juancaar** [comment]
Volvi a pasarme a la version original 0.2.5 y al parecer esa esta funcionando. Al parecer volvieron a lo que habia antes en subdivx porqie antes decia download y volvieon a colocar el "Bajar subtitulo ahora" . Probe el s0309 de rick and morty que por casualidad lo tenia y descargo los 4 subtitulos sin problema.

**Comment by Lanzheim** [comment]
Sí, desintalar y reinstalar funcionó

**Comment by cacafuti8888** [comment]
Correcto, la versión por defecto vuelve a funcionar. A ver si lo dejan como están... Gracias a todos, aprovecho para felicitar al autor del addon. Saludos

**Comment by matteraf** [comment]
Es como dice @juancaar, se ve que en estas horas que pasaron entre que algunos probamos el workaround y ellos volvieron atras el cambio, no se podían bajar los subs.
Gracias a todos!

**Comment by delima45** [comment]
Está funcionando otra vez. Lo acabo de probar y ya descarga. Muchas gracias a todos!!!!!!!!!!
Saludos desde Perú.

**Comment by safernandez666** [comment]
Hola Chicos! Alguno Sigue con Problemas?

`20:58:17.895 T:1274016672  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: search
20:58:26.838 T:1190130592  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: download
20:58:26.858 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpFIce_A
20:58:26.859 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpe4jGsu
20:58:26.859 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpM5jxzT
20:58:26.860 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpH0jHPj
20:58:26.860 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpyrgPdg
20:58:26.861 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpXMRZsw
20:58:26.861 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmph5JCMv
20:58:26.862 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp7e3o_O
20:58:26.862 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmphngOLh
20:58:26.863 T:1190130592 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmprzUVTk
20:58:29.680 T:1324344224   ERROR: OnDownloadComplete - Saving of subtitle /storage/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp9hcukR/Suits.S07E15.Tiny Violin.srt to special://temp/v..srt failed
20:58:34.589 T:1190130592   ERROR: Delete - Error deleting file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6.es.srt
20:58:34.591 T:1190130592   ERROR: Rename - Error renaming file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6..srt
20:58:35.544 T:1190130592   ERROR: Delete - Error deleting file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6.es.ssa
20:58:35.545 T:1190130592   ERROR: Rename - Error renaming file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6..ssa
20:58:36.482 T:1190130592   ERROR: Delete - Error deleting file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6.es.sub
20:58:36.483 T:1190130592   ERROR: Rename - Error renaming file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6..sub
20:58:37.426 T:1190130592   ERROR: Delete - Error deleting file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6.es.idx
20:58:37.428 T:1190130592   ERROR: Rename - Error renaming file https://s12.escdn.co/jg6nswhobjtu7m7cyyqfc3y7zfzkw5scndimzmexyoh3owzakzyjfeg2v5xq/v.mp4|Referer=http://estream.to/embed-g8hhvasfi0ei.html&User-Agent=Mozilla/5.0+(compatible;+MSIE+10.0;+Windows+NT+6.0;+WOW64;+Trident/6..idx
`

Yo estoy con estos! Alguno sabe que puedo hacer?

Abrazo

**Comment by Lanzheim** [comment]
Sip el addon no está funcionando desde hace como mes y medio o más. En mi caso encuentra los subs pero da error al descargarlos.

Alguno ha solucionado este inconveniente?

**Comment by safernandez666** [comment]
Estamos en la misma. Si pasas a la 0.25, descarga, pero no puede renombrar. Deberemos revisar...Una lastima.

**Comment by delima45** [comment]
Hola
Deben probar de instalar una o dos versiones anteriores, la 0.3.3 Lo que deben hacer es lo siguiente
1 Desinstalan la última versión  que tengan
2 Instalan la que les digo como lo hacen con cualquier addon.
3 Desactivan la opción de actualizar
4 iMPORTANTE, deben hacer una salida limpia de Kodi, es decir salir de Kodi vía EXIT. Si lo cierran sin hacer eso el programa que han puesto no se instala.

Me  funcionó perfecto. ´
Suerte.
Luis

**Comment by delima45** [comment]
Aclaracion, tengo la version 0.3.3 en Subdivx. Suerte

**Comment by safernandez666** [comment]
Gracias Luis, voy a probar. El Shutdown lo haces desde terminal? O del Front End?

**Comment by delima45** [comment]
Sales desde la página principal de Kodi, abajo a la izquierda están los botones de favoritos  y salir. Por si acaso, el bloqueo de actualizar lo hacen en configuración del addon Subdivx desenmarcando esa opción.

**Comment by Lanzheim** [comment]
Dónde consigo la versión 0.3.3 dentro de kodi la única opción que me da es la 0.3.0 ya la desinstalé y reinstalé y sigue igual. Encuentra, pero no baja subtitulos.

**Comment by Lanzheim** [comment]
Descargué la versión 0.2.5 y aparentemente funciona. Estoy en kodi 17.6

La versión 0.2.5 la encuentran aquí:
http://ftp.osuosl.org/pub/xbmc/addons/gotham/service.subtitles.subdivx/

**Comment by delima45** [comment]
Hola
No tenia donde guardar el file así que debí abrir cuenta en Mediafire. Te dejo el link. Es un archivo rar. Pásale el antivirus si deseas.
http://www.mediafire.com/file/2vl1c6bajok5112/service.subtitles.subdivx-0.3.3.zip

**Comment by Lanzheim** [comment]
Confirmo las versiones 0.2.5 y 0.3.3 funcionan perfectamente.

**Comment by ramiro** [comment]
Correcto,

Quienes tengan problemas con las version 0.3.0 pueden volver a la versión 0.2.5. O pueden instalar las versiones 0.3.1. a 0.3.4 que todavia no se publicaron en el repositorio de addons de Kodi

Los archivos .zip de todas ellas se pueden descargar de aca de GitHub. ver mas detalles en:

* https://github.com/ramiro/service.subtitles.subdivx/issues/35#issuecomment-378034092
* https://forum.kodi.tv/showthread.php?tid=209064&pid=2722259#pid2722259
