### ISSUE TITLE
v0.3.0 falla en Android + Kodi 17.x

### ISSUE THREAD

**Issue by IvanRF** [ramiro/service.subtitles.subdivx#35]
A partir de la versión 0.3.0 no descarga ningún subtítulo en Android (Kodi 17.6).
- Falla al borrar las carpetas temporales antiguas
- Falla al leer la extracción y querer copiar

Preview:
```
12:20:37.980 T:18446744072701868320  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: download
12:20:37.981 T:18446744072701868320   DEBUG: SUBDIVX - xbmc.translatePath(__addon__.getAddonInfo('profile')) (<type 'str'>): /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/
12:20:37.981 T:18446744072701868320   DEBUG: SUBDIVX - __profile__ (<type 'unicode'>): /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/
12:20:37.988 T:18446744072701868320 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp8rnRZP
12:20:37.989 T:18446744072701868320 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp696YHV
12:20:37.991 T:18446744072701868320 WARNING: SUBDIVX - _cleanup_tempdir: Failed to remove /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpfsUSNt
12:20:37.999 T:18446744072701868320   DEBUG: SUBDIVX - workdir (<type 'unicode'>): /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp35JDfq/
12:20:38.000 T:18446744072701868320   DEBUG: SUBDIVX - get_url: Fetching ZZZ
12:20:41.198 T:18446744072701868320   DEBUG: SUBDIVX - Download: Intermediate detail page for selected subtitle or expected content not found. Handling it as final download page
12:20:41.200 T:18446744072701868320   DEBUG: SUBDIVX - get_url: Fetching http://www.subdivx.com/bajar.php?id=223171&u=6
12:20:44.085 T:18446744072701868320   DEBUG: SUBDIVX - _save_subtitles: Saving subtitles to '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp35JDfq/subdivx.rar'
12:20:44.126 T:18446744072957720864   ERROR: Copy - Failed read from file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp35JDfq/ZZZ.srt
12:20:44.130 T:18446744072957720864   ERROR: OnDownloadComplete - Saving of subtitle /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.subtitles.subdivx/tmp35JDfq/ZZZ.srt to special://temp/ZZZ..srt failed
```

Log completo: [kodi.log](https://github.com/ramiro/service.subtitles.subdivx/files/1820020/kodi.log)

**Comment by matteraf** [comment]
Tambien falla en raspberry pi 3 Kodi 17.x

17:11:38.258 T:1429205760  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: download
17:11:40.783 T:1549792000   ERROR: OnDownloadComplete - Saving of subtitle /home/osmc/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpYDjgJq/Designated Survivor S02E13 HDTV x264-KILLERS.srt to special://temp/716..srt failed

**Comment by matteraf** [comment]
Podrias por favor indicarnos como instalar la versión anterior?  Gracias.

**Comment by ramiro** [comment]
@matteraf ¿Qué tipo de video estás tratando de ver? ¿Un streaming?

**Comment by matteraf** [comment]
si

**Comment by ramiro** [comment]
Desinstala la versión 0.3.0.

Descarga este .zip en tu dispositivo:  https://github.com/ramiro/service.subtitles.subdivx/archive/v0.2.5.zip

E instala ese .zip usando la función 'Instalar add-on desde un archivo.zip'

**Comment by matteraf** [comment]
El log completo, para que te sirva de ayuda:

17:46:41.568 T:1694495488  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.08a
17:48:25.450 T:1567879936  NOTICE: Previous line repeats 3 times.
17:48:25.450 T:1567879936 WARNING: Attempt to use invalid handle -1
17:48:27.159 T:1925478912  NOTICE: VideoPlayer: Opening: http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521319700~190.246.0.0~n1fFFjqG/716|Referer=http%3A%2F%2Ffruitstreams.com%2Fembed%2Fktbrcbmeeobkaaql&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A31.0%29+Gecko%2F20100101+Firefox%2F31.0
17:48:27.159 T:1925478912 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:48:27.731 T:1091564288  NOTICE: Creating InputStream
17:48:31.149 T:1091564288  NOTICE: Creating Demuxer
17:48:32.885 T:1091564288  NOTICE: Opening stream: 0 source: 256
17:48:32.886 T:1091564288  NOTICE: Creating video codec with codec id: 28
17:48:32.895 T:1091564288  NOTICE: Creating video thread
17:48:32.896 T:1351611136  NOTICE: running thread: video_thread
17:48:32.896 T:1091564288  NOTICE: Opening stream: 1 source: 256
17:48:32.897 T:1091564288  NOTICE: Finding audio codec for: 86018
17:48:32.899 T:1091564288  NOTICE: Creating audio thread
17:48:32.900 T:1445528320  NOTICE: running thread: CVideoPlayerAudio::Process()
17:48:32.912 T:1445528320  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
17:48:37.950 T:1351611136 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
17:48:43.378 T:1567879936 WARNING: Previous line repeats 2 times.
17:48:43.378 T:1567879936   ERROR: EXCEPTION: Unknown addon id 'script.trakt'.
17:48:43.399 T:1567879936   ERROR: Previous line repeats 2 times.
17:48:43.399 T:1567879936  NOTICE: metahandler: Initializing MetaHandlers version: 3.0.3
17:48:43.498 T:1567879936  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.21.0
17:48:43.528 T:1567879936  NOTICE: metahandler: No SQLite rows requiring update
17:48:46.253 T:1411973888  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: search
17:48:52.159 T:1411973888  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: download
17:48:54.687 T:1437139712   ERROR: OnDownloadComplete - Saving of subtitle /home/osmc/.kodi/userdata/addon_data/service.subtitles.subdivx/tmpDn1Isv/Designated Survivor S02E13 HDTV x264-KILLERS.srt to special://temp/716.es.srt failed

**Comment by matteraf** [comment]
Muchas gracias, quedó andando la 0.25 y le quité la opción de auto-update.

**Comment by ramiro** [comment]
@IvanRF @matteraf Es posible que les pida que instalen en sus dispositivos, prueben y reporten futuras versiones con modificaciones a 0.3.0 para ir tratando de solucionar esta regresión en Android/Raspi para Kodi 17.x

Se haría del miso modo como se puede instalar 0.2.5: Descargando un .zip desde GitHub e instalándolo. Luego pueden volver a 0.2.5 con al misma técnica.

¿Se animan?

**Comment by matteraf** [comment]
Me encantaría, pero estoy con una situación familiar que consume tiempo, ergo no dispongo del mismo al menos esta semana.

**Comment by IvanRF** [comment]
@ramiro sí, avisa acá cuando subas las modificaciones a github y lo pruebo

**Comment by yukatan** [comment]
Buenas, yo puedo probar también en RASP si lo necesitas

**Comment by ramiro** [comment]
Hola @IvanRF @matteraf y @yukatan Podrían por favor probar ya sea la versión 0.3.1 o la 0.3.2 ?
0.3.1 contiene lo que pienso es la solución para el problema que experimentan.

0.3.2 tiene un arreglo cosmético adicional que hace que los fallos no fatales en intentar borrar viejos directorios temporales no sean tan alarmantes cuando uno lee el log `kodi.log`.

Pueden instalar cualquier versión (incluso volver hacia 0.2.5) de la siguiente manera:

1. Descargar el archivo ZIP de la versión a instalar desde https://github.com/ramiro/service.subtitles.subdivx/releases seleccionando el enlace 'Source code (zip)' correspondiente
2. Desinstalar la versión actual de addon.
3.  Instalar el addon desde el archivo ZIP descargado en el paso 1 usando la opción de Kodi que permite instalar desde un archivo ZIP local.

Por favor comenten cómo les va.

¡Gracias!

**Comment by ramiro** [comment]
@Altaflux te pido que si es posible también ayudes probando las nuevas versiones.

> Hola @IvanRF @matteraf y @yukatan Podrían por favor probar ya sea la versión 0.3.1 o la 0.3.2 ?
> 0.3.1 contiene lo que pienso es la solución para el problema que experimentan.

**Comment by IvanRF** [comment]
@ramiro probé la versión 0.3.3 y ya está funcionando bien en Android de nuevo 👍
