### ISSUE TITLE
ERROR: OnDownloadComplete

### ISSUE THREAD

**Issue by matteraf** [ramiro/service.subtitles.subdivx#36]
Hola, la versión 0.3 me esta dando este error

16:50:04.755 T:1278210816  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: search
16:50:16.472 T:1278210816  NOTICE: SUBDIVX - Version: 0.3.0 -- Action: download
16:50:19.060 T:1141895936   ERROR: OnDownloadComplete - Saving of subtitle /home/osmc/.kodi/userdata/addon_data/service.subtitles.subdivx/tmphnwGL2/Designated Survivor S02E13 HDTV x264-KILLERS.srt to special://temp/716..srt failed
16:50:23.486 T:1278210816   ERROR: Delete - Error deleting file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31.es.srt
16:50:23.487 T:1278210816   ERROR: Rename - Error renaming file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31..srt
16:50:25.036 T:1278210816   ERROR: Delete - Error deleting file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31.es.ssa
16:50:25.037 T:1278210816   ERROR: Rename - Error renaming file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31..ssa
16:50:26.544 T:1278210816   ERROR: Delete - Error deleting file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31.es.sub
16:50:26.545 T:1278210816   ERROR: Rename - Error renaming file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31..sub
16:50:28.053 T:1278210816   ERROR: Delete - Error deleting file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31.es.idx
16:50:28.054 T:1278210816   ERROR: Rename - Error renaming file http://fruitstreams.com/v/d/ktbrcbmeeobkaaql~1521316041~190.246.0.0~pm1M-SXi/716|Referer=http://fruitstreams.com/embed/ktbrcbmeeobkaaql&User-Agent=Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:31.0)+Gecko/20100101+Firefox/31..idx

puedo volver a la 0.25?

**Comment by Altaflux** [comment]
Estoy teniendo este mismo problema desde hace unos dias.

**Comment by ramiro** [comment]
Por favor, incluir algo de informacion que permita razonar sobre el problema, tales como

* Sistema operativo (SO)
* Versión de SO
* Versión de Kodi

Reabrir este ticket con esa info, o ver si es un duplicado de #35.
