### ISSUE TITLE
Deseó obtener la versión 0.25 para Android, Kodi 17.6 .  Gracias

### ISSUE THREAD

**Issue by matteraf** [ramiro/service.subtitles.subdivx#37]
Gracias

**Comment by IvanRF** [comment]
Podes bajar cualquier versión desde la opción [Releases](https://github.com/ramiro/service.subtitles.subdivx/releases).

El .zip de esa versión está acá: https://github.com/ramiro/service.subtitles.subdivx/releases/tag/v0.2.5
