### ISSUE TITLE
ValueError: bad marshal data (digit out of range in long) en import html2text (Kodi 18 testing, raspberry pi 3)

### ISSUE THREAD

**Issue by Petemir** [ramiro/service.subtitles.subdivx#38]
Hola Ramiro, ¿cómo va?

Estoy teniendo problemas para usar el plugin, me pasaba con la v0.3.2 (venía andando bien, dejó de andar) usando el testbuild del día 01/05 de Libreelec Milhouse (kodi 18) ; recién probé con la v0.3.4 del plugin, el build de libreelec del día 09/07 y lo mismo. 

El error es el siguiente:

```
17:41:45.841 T:1371493232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>                                 
                                            Error Contents: bad marshal data (digit out of range in long)                                                          
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.subdivx/service.py", line 45, in <module>
                                                import html2text                          
                                            ValueError: bad marshal data (digit out of range in long)
                                            -->End of Python script error report<--
17:41:45.857 T:1809818480   ERROR: GetDirectory - Error getting plugin://service.subtitles.subdivx/?action=search&languages=English&preferredlanguage=Unknown
```

Cualquier info adicional que necesites, pedímela. Saludos y gracias por este gran plugin!

**Comment by ramiro** [comment]
¡Hola! ¿Es posible que hayan quedado archivos `.pyc` y similares de una versión previa de Python en el sistema de archivos y que luego de alguna actualización de SO y/o Python por alguna causa los mismos no puedan ser sobre-escritos por el nuevo interprete Python?

Los resultados de Googlear ese tipo de error:

  `ValueError: bad marshal data (digit out of range in long)`

apuntan hacia esa dirección.

El problema aparentemente es con los archivos del plugin `script.module.html2text` que es una dependencia de nuestro addon.

Trataría de encontrar todos los archivos `*.pyc` y `*.pyo` y también directorios `__pycache__` en `/storage/.kodi/addons` y sus subdirectorios y eliminarlos.

¿Sabes qué version de Python se usa en esa plataforma?

¿Tiene otros addons de Kodi instalados? ¿Funcionan?

**Comment by Petemir** [comment]
Hola, gracias por la rápida respuesta. 

Usa python 2.7.15 al menos en el build en el que estoy yo, y sí, tiene otros addons de Kodi (para bajar subtítulos -opensubtitles, podnapisi, argenteam-, los scrappers de contenido, el de youtube, uno de Netflix)... en general funcionan, son medio erráticos la verdad.

Encontré archivos de tipo pyo, si a alguien le sirve los borré haciendo:
```
cd ~/.kodi/addons && find . -type f -iname "*pyo" | xargs -i rm {}
```

Ahora no tira más error el plugin al intentar correrlo, aunque para dos archivos que intenté usarlo (Westworld.S01E01.The.Original.720p.WEB-DL.DD5.1.H.264-CasStudio.mkv, the.handmaids.tale.s01e01.720p.hdtv.x264-mtb.mkv) no anduvo, tuve que hacer búsqueda manual (y ahí sí ya aparecieron los resultados de subdivx).

No sé si querés debuggear eso, o si querés cerrar el issue (al fin y al cabo, está resuelto).

Gracias!

**Comment by ramiro** [comment]
SI te parece cerremos este issue y cuando puedas/si queres obtener y adjuntar un log del otro error que encontraste abrilo en otro issue.

**Comment by Petemir** [comment]
Ok, cierro este, si veo cómo encontrar algún log de lo otro (porque no genera error... simplemente no encuentra el subtítulo) lo abro.

Gracias!
