### ISSUE TITLE
Kodi 18 y subtitulos rar

### ISSUE THREAD

**Issue by pyro12** [ramiro/service.subtitles.subdivx#39]
Hay muchos personas que estan teniendo problemas con archivos rar.   Incluso despues de instalar y habilitar el addon libarchive, algunos rar funciona y otros no.  El addon vfs-rar parece no tener efecto. 

https://pastebin.com/uJz7mW4m

https://www.subdivx.com/X12X66X234075X0X0X1X-subtitulos-en-kodi-18.html

Estoy usando Linux Mint 19 y Kodi 18

```
apt-cache search kodi-vfs-
kodi-vfs-rar-dbg - debug symbols for RAR VFS for Kodi
kodi-vfs-rar - RAR VFS for Kodi
kodi-vfs-nfs-dbg - debug symbols for NFS VFS for Kodi
kodi-vfs-nfs - NFS VFS for Kodi
kodi-vfs-libarchive-dbg - debug symbols for libarchive VFS for Kodi
kodi-vfs-libarchive - libarchive VFS for Kodi
kodi-vfs-sftp-dbg - debug symbols for SFTP VFS for Kodi
kodi-vfs-sftp - SFTP VFS for Kodi
kodi-vfs-sacd-dbg - debug symbols for sacd VFS for Kodi
kodi-vfs-sacd - sacd VFS for Kodi
```

Gracias por cualquier ayuda

edit:  I want to add that I have updated to subdivx 0.3.5 and there is no apparent change in behavior.

**Comment by Edda22** [comment]
Estoy teniendo el mismo problema, pero lo empecé a notar luego de que kodi actualizara a la ver 18. Uso la Nvidia Shield tv.

**Comment by pyro12** [comment]
Hoy, hubo upates para libarchive (1.0.5.1) y vfsrar (2.05)! Aun asi, hay la misma problema

**Comment by ramiro** [comment]
Hasta donde entiendo, no se trata de un error en el add-on.

En Kodi 18 se ha introducido un cambio por el cual una función (`XBM.Extract()`) que antes se usaba para extraer archivos comprimidos cualquiera fuera el tipo (Rar, Zip) ya no funciona para archivos Rar que lamentablemente se usan mucho (¡exclusivamente?) en Subdivx.

Ahora para esa tarea deben usarse funciones como `xbmcvfs.listdir()`, `xbmcvfs.copy()`, etc. y por otra parte deben estar presentes los servicios del add-on binario oficial `vfs.libarchive`. Esto último algunos de Uds. ya lo han descubierto.

Nuestro add-on tiene las modificaciones necesarias para adaptarse a estos cambios desde la versión 0.2.10 de Marzo 2018.

Por otra parte `vfs.libarchive`, por razones de seguridad, es un add-on que no puede instalarse en forma automática (como usualmente sucede) al instalar un add-on como el nuestro aun cuando  este tiene declarada una dependencia de aquél (dependencia que para otros tipos de add-ons es la responsable de disparar su instalación automática por parte de Kodi). Es el usuario el que tiene que estar pre-avisado y debe instalarlo manual y explícitamente.

Hasta aquí los cambios.  Ahora hablemos sobre los problermas.

Mi hipótesis para intentar explicar los fallos con algunos archivos Rar y que no existan problemas con otros es la siguiente:

* Al tratarse de un add-on binario, los mismos poseen la implementación de las rutinas de descompresión de archivos rar en C u otro lenguaje similar.
* La distribución de la implementación de esas rutinas deja de estar bajo el control de Kodi. Cambia de acuerdo a la plataforma y hay disparidad: En algunas distribuciones Linux el add-on `vfs.libarchive` a su vez depende de alguna biblioteca de bajo nivel (`libarchive`) provista por el SO. Desconozco cómo se soluciona/implementa esto en Windows, LibreElec, Android, etc. pero lo cierto es que mas modularidad implica menos control por parte en este caso de Kodi y una falta de garantía para nuestro add-on de que todas las bibliotecas involucradas y sus versiones son correctas.
* Creo que lo que sucede es que algunos archivos Rar mas "modernos" creados con versiones mas nuevas de la herramienta oficial Rar deben tener en algún lugar de su header de archivo un campo de nro. de versión y las implementaciones de decompresión de algunas librerías de bajo nivel son mas antiguas y no saben cómo descomprimir esos .RAR mas modernos y por eso reportan inmediatamente un error.

Este no es el único add-on afectado por este cambio. Pueden ver mas casos en este foro:

https://forum.kodi.tv/forumdisplay.php?fid=143

Por ejemplo en este hilo:

https://forum.kodi.tv/showthread.php?tid=340841

También se puede ver mas información (técnica), por ejemplo, en este hilo (en el que participé realizando preguntas en Marzo de 2018):

https://forum.kodi.tv/showthread.php?tid=323321

En general Kodi 18 ha migrado a una arquitectura mas modular en la cual algunas funciones auxiliares (por ejemplo la descompresión) se han movido desde el programa a add-ons disponibles en el repositorio oficial. Incluso cuando uno instala Kodi 18 en Windows, aparece un cuadro de diálogo que avisa que el usuario debe encargarse de instalar manualmente todos los add-ons que hubiese usado en versiones previas.

**Comment by pyro12** [comment]
muchas gracias por tomarse el tiempo a hacer un explicacion tan detallada.  

Curiosamente, Ubuntu actualiza su libarchive la semana pasada.  No sirvio de nada.  :-(

Sere paciente y esperare una solucion.

**Comment by ikerfp** [comment]
Hola, tengo el mismo problema desde que se me actualizo a kodi 18.

Alguna solucion posible?

**Comment by ikerfp** [comment]
Ya me funciona instalando Archive support (by spiff) add-on y la versión 0.3.4 de subdivx addon

Gracias!!!!

**Comment by ikerfp** [comment]
> Hola, tengo el mismo problema desde que se me actualizo a kodi 18.
> 
> Alguna solucion posible?

Ya me funciona instalando Archive support (by spiff) add-on y la versión 0.3.4 de subdivx addon

Gracias!!!!

**Comment by ramiro** [comment]
@ikerfp Me alegro de que se haya solucionado.

Lamentablemente entiendo que lo que hay/había que hacer era esperar que se estabilizara un poco la situación con el add-on libarchive.

Creo que no es necesario correr versiones del add-on subdivx 0.3.3 o 03.4 (no lanzadas públicamente y que contienen cambios no relacionado con el manejo de archivos con subtítulos comprimidos). La versión 0.3.2 debería funcionar de igual manera.

@pyro12  ¿A ti también se te han solucionado los problemas que tenías?

**Comment by pyro12** [comment]
Sigue teniendo el mismo problema

Mencionaste anteriomente hay rars nuevos y viejos. Hay un dicusion en subdivx.com sobre esto.

https://www.subdivx.com/X12X66X234381X0X0X1X-pregunta-para-subtituladores-o-administradores.html

Lo parece el problema esta con los rar5.  

Me parace extrano que puedo descargar los subtiulos manualmente, descomprimirlos, y cargarlos en Kodi.  Gnome Archive Manager maneja estos archivos bien.

PERO, y lo esta muy extrano, despues de el subdivx plugin falle y hago clic "browse for subtitles..." el "working directory" o "default directory" (no se como se llama), se convierte en la url del video que estoy transmitiendo.  Kodi obviamente no puede abrir ese directorio, pero tengo que esperar a que se "timeout" antes de poder navegar mi hardrive. Puede ver el cambio del "working directory" en la pastebin anterior.  Esto no esta bien, no?

Muchas gracias por ayudame a comprender y arreglar esta problema.

No escrito ningun codigo (excepto unos BASH scriptos) desde antes de internet y esa ere PASCAL.  PYTHON parece limpio y podría tratar de aprenderlo.  Quiza puedo apprender eso idioma mejor que el espanol  :-)

**Comment by daniesteban** [comment]
Como comenta @ikerfp en https://github.com/ramiro/service.subtitles.subdivx/issues/39#issuecomment-466386356 para mi se solucionó simplemente activando el addon _Archive support (by spiff)_ dentro de los addons de Kodi, pero sin necesidad de actualizar el plugin de subdivx.

Probar esta solución si en kodi.log os aparecen mensajes del tipo:
`WARNING: Create - unsupported protocol(archive) in archive://%2Fhome%2Fosmc%2F.kodi%2Fuserdata%2Faddon_data%2Fservice.subtitles.subdivx%2FtmpxF6qps%2Fsubdivx.rar/`
`2019-04-26 18:30:47.546 T:1182917344  SEVERE: SUBDIVX - _handle_compressed_subs: Failed to unpack subtitles`

En resumen, funcionando en mi caso en osmc con kodi 18:
- subdivx 0.3.2, versión oficial del plugin en los repositorios de kodi
- Archive support activado en los addons de kodi

**Comment by IvanRF** [comment]
@ramiro me sumo, en Android con Kodi 18.2 instalé `Archive support` y para algunos subtítulos dejó de arrojar errores (no miré el log para ver si son zip o rar).

Siguiendo los links que mencionaste este plugin agrega la dependencia:
https://github.com/henricos/service.subtitles.legendastv/blob/master/addon.xml#L9

```
<requires>
   ...
    <import addon="vfs.libarchive" version="1.0.5" />
</requires>
```

No probé aún si ese cambio hace que Kodi 18 consulte al usuario si quiere instalar Archive support junto con el plugin, vos ya lo habías probado?

**Comment by didierco** [comment]
Instalé archive support y RAR archive support que se encuentran en la categoría virtual filesystems del kodi add-on repository. Hasta el momento está funcionando bien.

**Comment by ramiro** [comment]
Cerrando porque se confirma lo expresado en el comentario https://github.com/ramiro/service.subtitles.subdivx/issues/39#issuecomment-464533035

**Comment by ramiro** [comment]
Extra info , probably useful in the future:  Zach Morris has created a Kodi script/module/addon which abstracts compressed archive handling:  https://github.com/zach-morris/script.module.archive_tool

**Comment by ramiro** [comment]
Addons de subtitulos que a la fecha tienen updates hace menos de un año:

- https://github.com/xbmc/repo-scripts/tree/krypton/service.subtitles.rvm.addic7ed
- https://github.com/xbmc/repo-scripts/tree/gotham/service.subtitles.legendasdivx
- https://github.com/xbmc/repo-scripts/tree/gotham/service.subtitles.pipocas

(para revisar/comparar si declaran dependencia de vfs libarchive en addon.xml)
