### ISSUE TITLE
Problema bajando subtitulo

### ISSUE THREAD

**Issue by release-olx** [ramiro/service.subtitles.subdivx#4]
Cada vez que quiero bajar un subtitulo, tira un error de "Error Downloading Subtitle". La busqueda funciona bien por lo general. Estoy corriendo sobre Kodi/OSMC ultima version, la version del add-on tambien es la ultima.

**Comment by upadrian** [comment]
Es el mismo error que reporté yo este fin de semana pasado. 
En la versión beta de Isengard no me pasa, quizás sea un bug en el kodi mismo.
Yo estoy corriendo kodi/openelec en raspberry pi 2

**Comment by codigonegro** [comment]
Al activar el log del kodi, aparece este error:

```
14:50:56 T:1582298144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 49: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py", line 531, in <module>
                                                main()
                                              File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py", line 510, in main
                                                ensure_workdir(workdir)
                                              File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py", line 361, in ensure_workdir
                                                shutil.rmtree(workdir)
                                              File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
                                                fullname = os.path.join(path, name)
                                              File "/usr/lib/python2.7/posixpath.py", line 78, in join
                                                path +=  b
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 49: ordinal not in range(128)
                                            -->End of Python script error report<--
14:50:56 T:1952850704   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
14:50:56 T:1582298144    INFO: Python script stopped
```

¿Cómo se podría arreglar?

**Comment by ramiro** [comment]
Estimados,

Prometo revisar estos casos en los proximos dias.

Seria muy útil si pueden pegar los nombres completos de los archivos de
video que están tratando de reproducir cuando se presentan los errores.

Gracias.

On Tue, May 19, 2015 at 11:56 AM, codigonegro notifications@github.com
wrote:

> Al activar el log del codi, aparece este error:
> 
> 14:50:56 T:1582298144 ERROR: EXCEPTION Thrown (PythonToCppException) :
> -->Python callback/script returned the following error<--
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>   Error Type:
>   Error Contents: 'ascii' codec can't decode byte 0xc3 in position 49:
>   ordinal not in range(128)
>   Traceback (most recent call last):
>   File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py",
>   line 531, in
>   main()
>   File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py",
>   line 510, in main
>   ensure_workdir(workdir)
>   File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py",
>   line 361, in ensure_workdir
>   shutil.rmtree(workdir)
>   File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
>   fullname = os.path.join(path, name)
>   File "/usr/lib/python2.7/posixpath.py", line 78, in join
>   path += b
>   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 49:
>   ordinal not in range(128)
>   -->End of Python script error report<--
>   14:50:56 T:1952850704 DEBUG: ------ Window Init (DialogKaiToast.xml) ------
>   14:50:56 T:1582298144 INFO: Python script stopped
> 
> ¿Cómo se podría arreglar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ramiro/service.subtitles.subdivx/issues/4#issuecomment-103536709
> .

## 

Ramiro Morales
@ramiromorales

**Comment by codigonegro** [comment]
Bueno en realidad parece estar ocurriendo con todos los subtitulos de subdivx. 
Por ejemplo con este:
URL de la Busqueda (los resultados se ven ok en el pluguin):
http://www.subdivx.com/X6XMjQwODUzX-game-of-thrones-s01e01.html

Enlace de descarga (primer resultado)
http://www.subdivx.com/bajar.php?id=240853&u=7

Nombre del archivo: 240853.rar

Log del Error:

```
21:01:17 T:1582298144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 49: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py", line 531, in <module>
                                                main()
                                              File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py", line 510, in main
                                                ensure_workdir(workdir)
                                              File "/var/lib/kodi/.kodi/addons/service.subtitles.subdivx/service.py", line 361, in ensure_workdir
                                                shutil.rmtree(workdir)
                                              File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
                                                fullname = os.path.join(path, name)
                                              File "/usr/lib/python2.7/posixpath.py", line 78, in join
                                                path +=  b
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 49: ordinal not in range(128)
                                            -->End of Python script error report<--
21:01:17 T:1608512544   ERROR: GetDirectory - Error getting plugin://service.subtitles.subdivx/?action=download&filename=http%3a%2f%2f192.168.0.102%3a65251%2ffiles%2fGame.of.Thrones.S01E01.FRENCH.LD.HDTV.XviD-JMT%2fgame.of.thrones.s01e01-jmt.avi&id=X6XMjQwODUzX-game-of-thrones-s01e01
21:01:19 T:1684005920  NOTICE: [plugin.video.pulsar] 2015-05-19 21:01:19  INFO  torrentfs        Waiting for piece 30
```

Espero que sirva de algo, saludos y gracias

**Comment by jdavisonc** [comment]
Estoy experimentando el mismo problema en Android Kodi Isengard al bajar cualquier subtitulo.

**Comment by luraschi8** [comment]
Ramiro, el problema aparece cuando el nombre del archivo .srt descomprimido posee caracteres que no son utf-8. Por lo que cuando haces una llamada del tipo decide("utf-8") se rompe y deja los archivos en el directorio temp generando que las próximas descargas también fallen.

Intente arreglarlo agregando este metodo:

``` python
def removeNonAscii(s): return "".join(i for i in s if ord(i)<128)
```

y llamándolo dentro de:

``` python
def _handle_compressed_subs(workdir, compressed_file):
    MAX_UNZIP_WAIT = 15
    files = os.listdir(workdir)
    filecount = len(files)
    max_mtime = 0
    # Determine the newest file
    for fname in files:
        if not is_subs_file(fname):
            continue
        mtime = os.stat(pjoin(workdir, fname)).st_mtime
        if mtime > max_mtime:
            max_mtime = mtime
    base_mtime = max_mtime
    # Wait 2 seconds so that the unpacked files are at least 1 second newer
    time.sleep(2)
    xbmc.executebuiltin("XBMC.Extract(%s, %s)" % (
                        compressed_file.encode("utf-8"),
                        workdir.encode("utf-8")))
    retval = False
    if _wait_for_extract(workdir, filecount, base_mtime, MAX_UNZIP_WAIT):
        files = os.listdir(workdir)
        for fname in files:
            # There could be more subtitle files, so make
            # sure we get the newly created subtitle file
            if not is_subs_file(fname):
                continue
            nonasciiname = removeNonAscii(fname)
            os.rename(fname, nonasciiname)
            fpath = pjoin(workdir, nonasciiname.decode("utf-8"))
            if os.stat(fpath).st_mtime > base_mtime:
                # unpacked file is a newly created subtitle file
                retval = True
                break

    if retval:
        log(u"Unpacked subtitles file '%s'" % fpath)
    else:
        log(u"Failed to unpack subtitles", level=LOGSEVERE)
    return retval, fpath
```

La idea era renombrar el archivo sacándole todos los caracteres que no sean utf-8 para que pueda continuar el proceso pero no parece andar, de hecho el archivo queda con el mismo nombre con lo que no estoy logrando renombrar el archivo. No pude hacer andar el debugger de forma remota con lo que me trabe en el fix.

Pero creo que por ahí anda la solución al problema. Cualquier cosa avísame y te doy una mano en lo que pueda.

**Comment by ramiro** [comment]
@luraschi8 

En realidad creo que ese problema que vos reportas se presenta despues, cuando realmente se descarga el subtítulo.

El error reportado en este issue es de cuando recien esta arrancando la acción de descarga (cuando el usuario selecciona un subtítulo de la lista) y se está limpiando el directorio temporal usado para contener las descargas.

**Comment by ramiro** [comment]
I think this has been fixed or at least worked around in 3c90853c793f6847e2d6f9e2867147661e66d2cb

**Comment by ramiro** [comment]
#8 also contained some changes in this area.
