### ISSUE TITLE
Help to migrate to subliminal

### ISSUE THREAD

**Issue by braian87b** [ramiro/service.subtitles.subdivx#40]
Hi @ramiro, spanish speaker here from Buenos Aires if you prefer.

I was poking around using _subliminal_ more info here: https://github.com/Diaoul/subliminal/
it is a cool tool to download subtitles from multiple sources aka _"providers"_ as their are called like that in _subliminal_

Since I usually use www.subdivx.com I wanted to make it work with it, but it doesn't have support yet: https://github.com/Diaoul/subliminal/issues/279

So I wanted to try to add support by my self but then I found your plugin/service and I wanted to ask you for some help since it seems that you managed to deal very well with the parsing / download and all that so I wanted to ask you if you had that fresh in your mind to be able to help, if you want to do so.

Thanks in advance.

**Comment by avraham** [comment]
I made a fork of subliminal and added subdivx as a provider.
The provider requires a subdivx account.

https://github.com/avraham/subliminal/tree/subdivx_provider

**Comment by ramiro** [comment]
Unfortunately this is out of scope for this project.
