### ISSUE TITLE
Icono del idioma

### ISSUE THREAD

**Issue by IvanRF** [ramiro/service.subtitles.subdivx#45]
Ramiro, cuál es tu opinión respecto a indicar que los subtítulos están en español?

Calculo que el 99% de los resultados de subdivx son subtítulos en español.

Mi idea era diferenciar los de Español España de los Español Latinoamérica en base a los comentarios del que lo sube, pero estoy viendo que Kodi usa ISO 639-1 y la única opción es usar 'es'.

Hay algunos subtítulos en inglés, pero en base a la descripción algunos ponen "traducidos del original en inglés" por lo que si la descripción incluye la palabra "inglés" no sería un indicador de que el subtítulo esté en inglés.

Línea https://github.com/ramiro/service.subtitles.subdivx/blob/master/service.py#L295

Una posible mejora es cambiar por: `thumbnailImage='es'`.

Info:
- https://github.com/xbmc/generator-kodi-addon/blob/master/generators/app/templates/resources/lib/subtitle.py#L102
```
# Languange 2 letter name (for example en)
thumbnailImage=xbmc.convertLanguage(language, xbmc.ISO_639_1))
```

**Comment by ramiro** [comment]
Iván, creo que has detallado muy bien cuales es el trabajo que habría que tener listo antes de poder (re)activar las columnas que muestran:
* El código de lenguaje 'es'
* La bandera española

Esto es, la lógica para poder detectar con una robustez aceptable el idioma del subtítulo.

La eliminación de ambas columnas se hizo en forma explícita para poder aprovechar mejor el espacio que ocupaban en pantalla (desde el addon no tenemos control sobre el tamaño del diálogo modal que Kodi muestra y el espacio disponible es muy reducido). No vale la pena tener un listado de subtítulos encontrados que tienen todos los mismos valores en ambas columnas.

Es mucho más útil poder usar ese espacio para ver el rating de hasta 5 estrellas del subtítulo según los usuarios de Subdivx, el nick del traductor y la descripción de texto que el traductor escribió.

Esos cambios se hicieron en:

* c1be6354fa592c58b3d881a2f4f00b5ff1eadd8b
* ef0e9ce7c0f562f959e2889cc14f88d7d438ce0c
