### ISSUE TITLE
Dejo de funcionar

### ISSUE THREAD

**Issue by ManuuelC** [ramiro/service.subtitles.subdivx#46]
El addon dejo de funcionar en Kodi 18.7 Leia, no encuentra ningún subtítulo de ninguna película. Al parecer hubo alguna actualización en Subdivx que dañó el add-on.

**Comment by vitiko98** [comment]
Aparentemente es un problema con Cloudfare y su método _anti-bots_.

**Comment by ramiro** [comment]
Exactamente. Justamente eso veia esta mañaña cuando entré a subdivx.com después de un par de años.

Dos cosas que aparentemente sucedieron recientemente en el sitio:

1. Pasaron de `http://` a `https://`
2.  Lo hicieron contratando/usando el servicio de Cloudflare (CF)

El punto 1 significa que por lo menos hay que realizar esa modificación al addon. Y probar si eso soluciona el funcionamiento.

Lamentablemente, sospecho que eso no va a funcionar debido al punto 2. En caso de que quisieramos arreglarlo, hay que investigar si hay alguna forma de evitar CF o adaptarse a su presencia. Nninguna de ellas debe ser sencilla ya que justamente la razón de la existencia de CF es evitar el acceso de todo lo que no sea una persona con un browser usando el sitio de forma interactiva.

De todos modos, por los comentarios que se leen en el foro, aparentemente la percepción que hay en los usuarios de Subdivx es que al sitio no le quedaría mucha vida. Ya comentan incluso sobre 2 o 3 sitios potenciales los cuales migrar en busqueda de subtítulos.

De modo que hay que evaluar qué futuro tiene el addon en base a todas estas novedades.

**Comment by ramiro** [comment]
https://github.com/venomous/cloudscraper
https://github.com/jairoxyz/script.module.cloudscraper

**Comment by IvanRF** [comment]
> Lamentablemente, sospecho que eso no va a funcionar debido al punto 2. En caso de que quisieramos arreglarlo, hay que investigar si hay alguna forma de evitar CF o adaptarse a su presencia. Nninguna de ellas debe ser sencilla ya que justamente la razón de la existencia de CF es evitar el acceso de todo lo que no sea una persona con un browser usando el sitio de forma interactiva.

@ramiro creo que eso podría solucionarse usando el header para "User-agent". Por lo que veo en el código está tapado.

https://stackoverflow.com/questions/27652543/how-to-use-python-requests-to-fake-a-browser-visit

**Comment by ramiro** [comment]
> @ramiro creo que eso podría solucionarse usando el header para "User-agent". Por lo que veo en el código está tapado.
> 
> https://stackoverflow.com/questions/27652543/how-to-use-python-requests-to-fake-a-browser-visit

Hola Iván.

¿Probaste y te funcionó? Yo lo hice con el user agente que terniamos comentado en el código y con algún otro más actual y no solucionó el problema.

Suena lógico. Sería dificil que CF fuera una empresa tan grande y ganara los millones que gana si fuese tan fácil esquivar sus chequeos anti bots DoS. Por lo que se lee en la doc del proyecto que llinkee arriba, se necesitan medidas mas complejas para esquivarlo.

**Comment by ramiro** [comment]
script.module.cloudscrapper no está disponible en los repositorios oficiales de Addons de Kodi :disappointed:

**Comment by vitiko98** [comment]
El agente no cambiaría nada. Es un problema de JS, según tengo entendido. 

Acabo de probar [cloudcraper](https://github.com/venomous/cloudscraper) y ha sido capaz de superar el bloqueo de Cloudflare:

```python
import cloudscraper
from bs4 import BeautifulSoup as bso

scraper = cloudscraper.create_scraper()
test_subdivx = scraper.get("https://www.subdivx.com/index.php?buscar=(...)")

soup = bso(test_subdivx.content, 'html.parser')
title = soup.find_all(id='menu_titulo_buscador')
[print(t.text) for t in title]
```
Resultado:
```
Subtitulos de Taxi Driver (1976)
Subtitulos de Taxi Driver (1976)
Subtitulos de Taxi Driver (1976)
(...)
```

Edit: Me pareció raro que funcione a la primera, así que probé con `requests` y también funcionó. No sé si este es un caso excepcional, porque he intentado lo mismo esta mañana sin suerte. Estaría bueno que alguien más probara de nuevo el addon.

**Comment by ramiro** [comment]
> Edit: Me pareció raro que funcione a la primera, así que probé con `requests` y también funcionó. No sé si este es un caso excepcional, porque he intentado lo mismo esta mañana sin suerte. Estaría bueno que alguien más probara de nuevo el addon.

Es muy probable que CF te haya habilitado en base a tu dirección IP por cierto tiempo luego de que pasaste la verificación vía Cloudscraper.

Lamentablemente al no estar disponible en los repor oficiales de Kodi se complica la situación. No quisiera tener que dirigir a los usuarios a descargar addons de dependencias de repos no oficiales y mucho menos a instalar cosas desde GitHub.

Y de todos modos por lo que leo en los issues de cloudscraper aparentemente no puede mantener el ritmo con las mejoras que va implementando CF asi que de todos modos no se si vale la pena el esfuerzo de incorporarlo como dependencia.

**Comment by vitiko98** [comment]
@ramiro, acabo de probar en un servidor remoto via SSH y ha vuelto a funcionar sin ningún error. ¿Será que Subdivx lo solucionó esta tarde? Hay que seguir testeando.

**Comment by vitiko98** [comment]
Probé nuevamente Kodi en Xbox y en Linux. El addon sigue sin funcionar. :/

**Comment by vitiko98** [comment]
Subdivx está repleto de spam: https://www.subdivx.com/X21X65X3X0X-foro-otros-sitios.html. Parece que esta es la causa de sus intentos de bloqueo.

**Comment by pablosambuco** [comment]
Buenas, hice algunas pruebas con cloudscraper y logré hacer funcionar el addon...
Los cambios que apliqué son:
- cambiar http por https en **todas** las apariciones
- al QS_DICT le agregué parámetros que noté en la URL de búsqueda: subtitulos y realiza_b, ambos con valor 1
- acomodé un poco el armado de la expresión regular que busca los items... quizás sea solo TOC mío y no haga falta el cambio:
```python
SUBTITLE_RE = re.compile(r'''<a\s+class="titulo_menu_izq"\shref="https://www.subdivx.com/(?P<subdivx_id>.+?)\.html">
                         .+?<img\s+src="img/calif(?P<calif>\d)\.gif"\s+class="detalle_calif"\s+name="detalle_calif">
                         .+?<div\s+id="buscador_detalle_sub">(?P<comment>.*?)</div>
                         .+?<b>Downloads:</b>(?P<downloads>.+?)<b>Cds:</b>
                         .+?<b>Subido\spor:</b>\s*<a.+?>(?P<uploader>.+?)</a>.+?</div></div>''',
                         re.IGNORECASE | re.DOTALL | re.VERBOSE | re.UNICODE | re.MULTILINE)
```
- cambié el uso de get_url por create_scraper + get:
```python
    scraper = cloudscraper.create_scraper()
    content=scraper.get(url).text
```
- saqué el chequeo de "not SUBTITLE_RE.search(content)", siempre devuelve None, pero el finditer que se usa después no tiene problemas. De última devuelve un iterator vacío
- a raw_desc le saqué el decode... al parecer algo cambió y toda la página está en correcto utf-8

También, para que el addon no falle al cargar, agregué la dependencia con cloudscraper en el addon.xml:
```xml
<import addon="script.module.cloudscraper" version="1.2.46"/>
```

Espero que el aporte sirva
Saludos!

**Comment by ramiro** [comment]
> Buenas, hice algunas pruebas con cloudscraper y logré hacer funcionar el addon...
> Los cambios que apliqué son:
> - cambiar http por https en **todas** las apariciones
> - al QS_DICT le agregué parámetros que noté en la URL de búsqueda: subtitulos y realiza_b, ambos con valor 1
> - acomodé un poco el armado de la expresión regular que busca los items... quizás sea solo TOC mío y no haga falta el cambio:
> ```python
> SUBTITLE_RE = re.compile(r'''<a\s+class="titulo_menu_izq"\shref="https://www.subdivx.com/(?P<subdivx_id>.+?)\.html">
>                          .+?<img\s+src="img/calif(?P<calif>\d)\.gif"\s+class="detalle_calif"\s+name="detalle_calif">
>                          .+?<div\s+id="buscador_detalle_sub">(?P<comment>.*?)</div>
>                          .+?<b>Downloads:</b>(?P<downloads>.+?)<b>Cds:</b>
>                          .+?<b>Subido\spor:</b>\s*<a.+?>(?P<uploader>.+?)</a>.+?</div></div>''',
>                          re.IGNORECASE | re.DOTALL | re.VERBOSE | re.UNICODE | re.MULTILINE)
> ```
> - cambié el uso de get_url por create_scraper + get:
> ```python
>     scraper = cloudscraper.create_scraper()
>     content=scraper.get(url).text
> ```
> - saqué el chequeo de "not SUBTITLE_RE.search(content)", siempre devuelve None, pero el finditer que se usa después no tiene problemas. De última devuelve un iterator vacío
> - a raw_desc le saqué el decode... al parecer algo cambió y toda la página está en correcto utf-8
> 
> También, para que el addon no falle al cargar, agregué la dependencia con cloudscraper en el addon.xml:
> ```xml
> <import addon="script.module.cloudscraper" version="1.2.46"/>
> ```
> 
> Espero que el aporte sirva
> Saludos!

¡Muy buen trabajo Pablo muchas gracias por hacer esa prueba!

Asumo que a cloudscraper lo instalaste manualmente o desde algún repositorio de addons externo. ¿Es así?

Me olvidé de actualizar por acá que hace unos días dejé la pregunta sobre si el usuario que empaquetó cloudscraper como add-on Kodi piensa subirlo al repo oficial Kodi, espero rta.: https://github.com/jairoxyz/script.module.cloudscraper/issues/3

Creo que esa es la condición imprescindible para poder avanzar con esto.

La otra posibilidad que veo sería ese instalador de addons directo desde repos GitHub que han creado los de un sitio muy famoso de addons no oficiales. Pero habría que ver si no tenemos una situación huevo-gallina porque si para poder usar ese instalador el usuario tiene que agregar un repo no oficial a Kodi y como parte de ese proceso se le instalan n addons de dudosa procedencia al fínal estamos en la misma situación que es la que me gustaría evitar: Arriesgar a los usuarios dándole instrucciones que para colmo van a ser complejas para que instalen cosas extras y hasta ilegales.

¿Alguien tiene experiencia con ese instalador?

**Comment by pablosambuco** [comment]
@ramiro, bajé el zip del repositorio de jairoxyz y lo instalé a mano en kodi desde el menu de addons
La verdad no usé nunca el instalador que mencionás.
Tengo algunos repos externos, pero no me fijé si existía el paquete ahí

Saludos!

**Comment by mcflai** [comment]
> Buenas, hice algunas pruebas con cloudscraper y logré hacer funcionar el addon...
> Los cambios que apliqué son:
> 
> * cambiar http por https en **todas** las apariciones
> * al QS_DICT le agregué parámetros que noté en la URL de búsqueda: subtitulos y realiza_b, ambos con valor 1
> * acomodé un poco el armado de la expresión regular que busca los items... quizás sea solo TOC mío y no haga falta el cambio:
> 
> ```python
> SUBTITLE_RE = re.compile(r'''<a\s+class="titulo_menu_izq"\shref="https://www.subdivx.com/(?P<subdivx_id>.+?)\.html">
>                          .+?<img\s+src="img/calif(?P<calif>\d)\.gif"\s+class="detalle_calif"\s+name="detalle_calif">
>                          .+?<div\s+id="buscador_detalle_sub">(?P<comment>.*?)</div>
>                          .+?<b>Downloads:</b>(?P<downloads>.+?)<b>Cds:</b>
>                          .+?<b>Subido\spor:</b>\s*<a.+?>(?P<uploader>.+?)</a>.+?</div></div>''',
>                          re.IGNORECASE | re.DOTALL | re.VERBOSE | re.UNICODE | re.MULTILINE)
> ```
> 
> * cambié el uso de get_url por create_scraper + get:
> 
> ```python
>     scraper = cloudscraper.create_scraper()
>     content=scraper.get(url).text
> ```
> 
> * saqué el chequeo de "not SUBTITLE_RE.search(content)", siempre devuelve None, pero el finditer que se usa después no tiene problemas. De última devuelve un iterator vacío
> * a raw_desc le saqué el decode... al parecer algo cambió y toda la página está en correcto utf-8
> 
> También, para que el addon no falle al cargar, agregué la dependencia con cloudscraper en el addon.xml:
> 
> ```
> <import addon="script.module.cloudscraper" version="1.2.46"/>
> ```
> 
> Espero que el aporte sirva
> Saludos!

Que tal Pablo, tendras el service.py para compartir? intente replicar lo que comentas pero solo obtengo el listado, no logro descargar el subtitulo. Gracias!

**Comment by pablosambuco** [comment]
hola mcflai, es verdad... asumí que porque había generado un archivo ya estaba funcionando, pero seguramente el paso de descarga también necesite un ajuste. El archivo que genera es el log de error del bajar.php por no tener todas las variables definidas

Una idea (desesperada) es probar si el archivo es .rar o .zip armando las 2 opciones de URL posibles (bajar.php solamente parece buscar cuál es el nombre correcto del archivo y reescribe la URL)
Algo asi:
```python
actual_subtitle_file_url = MAIN_SUBDIVX_URL + "sub" + u + "/" + id_ + "." + ext
```
Voy a seguir probando si puedo hacerlo andar de alguna manera más elegante que prueba y error

*edit:
Finalmente fui por un loop tratando primero de bajar .rar y luego .zip, con la URL que deberia resolver el bajar.php ya que no logré completar todas las variables que necesita...
Adjunto acá el script funcionando: 
[service.py.zip](https://github.com/ramiro/service.subtitles.subdivx/files/5253159/service.py.zip)

**Comment by Expolio** [comment]
Hola buenas probe el zip dejado por @pablosambuco y no me deja instalarlo ,hay alguna forma actual de hacer que funcione el add on?

**Comment by pablosambuco** [comment]
Hola @Expolio, no te funciona porque se agrega una dependencia con un addon que no está en el repositorio oficial de Kodi.
Ramiro ya le preguntó al que mantiene ese addon si tiene planeado publicarlo, pero aún no hay respuesta: 
https://github.com/jairoxyz/script.module.cloudscraper

**Comment by mcflai** [comment]
Uhh no habia visto el edit con el zip!

Un detalle, tuve que cambiar el import de nombre a **cloudscraper2** que es como lo menciona en el repo del script también, tendrás algo diferente?

Luego de eso funcionó, gracias!

**Comment by pablosambuco** [comment]
@mcflai puede ser que lo haya cambiado en alguna prueba y me quedó así. Lo correcto es lo que decís **cloudscraper2**.

**Comment by tuxitos** [comment]
Buscando el subtitulo sobre https y bajandolo dela url "/sub" + u + "/" + id_ + ".rar" probando si es rar o zip funciona sin necesidad de cloudscraper2, les dejo el archivo por si les interesa mejorar esta idea ya que seguro hay mejor forma y python no es mi fuerte, saludos

[service.py.zip](https://github.com/ramiro/service.subtitles.subdivx/files/5273024/service.py.zip)

**Comment by Expolio** [comment]
> Hola @Expolio, no te funciona porque se agrega una dependencia con un addon que no está en el repositorio oficial de Kodi.
> Ramiro ya le preguntó al que mantiene ese addon si tiene planeado publicarlo, pero aún no hay respuesta:
> https://github.com/jairoxyz/script.module.cloudscraper

No consigo hacer que funcione, instalo el cloudscape y después cogí el service.py y lo sustituí por el del add on normal, tengo que hacer alguna modificación más?.

**Comment by Expolio** [comment]
> Uhh no habia visto el edit con el zip!
> 
> Un detalle, tuve que cambiar el import de nombre a **cloudscraper2** que es como lo menciona en el repo del script también, tendrás algo diferente?
> 
> Luego de eso funcionó, gracias!

logre cambiar el import y añadir la linea en el addon.xml ,me muestra la lista de subtitulos ,pero no lo descarga.
Alguna idea? Un Saludo ,Gracias!

**Comment by dmgmit** [comment]
Una pequeña contribución por parte mía. Tome el service.py de tuxitos. No fucionaba. Haciendo pruebas comprobé que por ejemplo la serie The boys s01e01 tomaba la extensión The boys s01e01.mkv en este caso mkv. A la hora de ejecutar la búsqueda que hace service.py https://www.subdivx.com/index.php?q=the+boys+s01e01.mkv&masdesc=&accion=5&oxdown=1 no devolvía resultados. Sin embargo quitando la extensión .mkv sí que daba resultados https://www.subdivx.com/index.php?q=the+boys+s01e01&masdesc=&accion=5&oxdown=1. Solución modificar la línea item['title'] = (normalize_string(xbmc.getInfoLabel("VideoPlayer.Title"))[:-4]) . De esta forma me devuelve lista  de resultados.

**Comment by dmgmit** [comment]
Quisiera contribuir a la solución. He probado el service.py de tuxitos y no funcionaba. Debugueándolo me di cuenta que por ejemplo en la serie the boys s01e01 service.py tomaba la extensión para buscar resultados, en este caso .mkv https://www.subdivx.com/index.php?q=the+boys+s01e01.mkv&masdesc=&accion=5&oxdown=1 y devolvía cero resultados. Sin embargo quitando la extensión .mkv https://www.subdivx.com/index.php?q=the+boys+s01e01&masdesc=&accion=5&oxdown=1 sí que devuelve resultados. Solución: modificar la línea  item['title'] = (normalize_string(xbmc.getInfoLabel("VideoPlayer.Title"))[:-4]). De esta manera tenemos lista de resultados.

**Comment by vitiko98** [comment]
> Buscando el subtitulo sobre https y bajandolo dela url "/sub" + u + "/" + id_ + ".rar" probando si es rar o zip funciona sin necesidad de cloudscraper2, les dejo el archivo por si les interesa mejorar esta idea ya que seguro hay mejor forma y python no es mi fuerte, saludos
> 
> [service.py.zip](https://github.com/ramiro/service.subtitles.subdivx/files/5273024/service.py.zip)

Probé tu `service.py` y funciona bien. El scraper anti-bots ya no es necesario.

Deberías abrir una pull request

**Comment by methodmann** [comment]
El service. Py funciona perfectamente. Muchas gracias por el gran trabajo que hacen.

**Comment by kralizeck** [comment]
> Buscando el subtitulo sobre https y bajandolo dela url "/sub" + u + "/" + id_ + ".rar" probando si es rar o zip funciona sin necesidad de cloudscraper2, les dejo el archivo por si les interesa mejorar esta idea ya que seguro hay mejor forma y python no es mi fuerte, saludos
> 
> [service.py.zip](https://github.com/ramiro/service.subtitles.subdivx/files/5273024/service.py.zip)

Funciona de lujo, sólo cambiando el service.py original por el tuyo.

¡Gracias @tuxitos!

**Comment by tuxitos** [comment]
Gracias por la retroalimentación, hare el pull request para que los administradores de repositorio revisen y decidan si aceptan mis cambios, saludos

**Comment by ps2reality** [comment]
Muchas gracias, reemplaze el service.py dentro de la carpeta del add-on y funciono 10 puntos !!!

**Comment by gboado** [comment]
Un detalle: si u = 1 el directorio no es sub1 sino sub. Me salt{o el error buscando un subtítulo que justamente encajaba con ese patrón. La soluci{on es un simple if después del match:

    id_, u = match.group('id', 'u')
    if u == '1':
       u = ''

**Comment by kralizeck** [comment]
Gracias, @gboado
No tenga nada de experiencia en python y, poiniendo tal cual tu código, me daba error de indentación, así que acabé usando el operador ternario:

`    id_, u = '' if u == '1' else match.group('id', 'u')
`

**Comment by ramiro** [comment]
Solucionado en a665285 ¡Gracias a @tuxitos  @gboado y todo quienes colaboraron!

Disponible en la versión 0.3.6 del add-on que ya está en el repo oficial de add-ons Kodi
