### ISSUE TITLE
Subdivx dejó de funcionar

### ISSUE THREAD

**Issue by gboado** [ramiro/service.subtitles.subdivx#54]
El sitio subdivx cambió radicalmente de interface y el addin dejó de funcionar completamente.

**Comment by ramiro** [comment]
De https://github.com/ramiro/service.subtitles.subdivx/issues/48#issuecomment-1945789476

**Resumen: El addon quedó desactualizado con el nuevo diseño de subdivx, no va a encontrar resultados. Es muy probable que este sea el final del addon.** 

Volvió el sitio y la performance es mucho mejo, el diseño es mas moderno.

Desafortunadamente hay cosas que harían imposible o dificultarían mucho adaptar el addon Kodi a la nuevas tecnologías usadas:
* Si uno realiza una búsqueda de subtítulos con palabras claves como anónimo (sin haberse logueado con usuario y contraseña al sitio) sólo muestra 10 resultados. Antes era posible realizar búsquedas anónimamente y es lo que hacía el addon
* Si uno se loguea, la página de búsqueda/resultados de búsqueda es una SPA (¿que probablemente usa React o similar?) de manera que por ejemplo:
   - El envío de la petición de búsqueda con dichas palabras claves
   - El uso de la UI de paginación en los resultados de búsqueda
   - Cambiar el tamaño de cada pagina
   - etc.,

están todas basada en una interacción que sólo puede implementar un browser con su motor Javascript.

De manera que veo difícil poder adaptar el addon para que pueda consumir el nuevo sitio con las herramientas disponibles en el ecosistema de librerías usables por addons Kodi.

Estoy tratando de averiguar si el sitio tienen una API que se pueda usar.

Por ahí otra posibilidad a explorar, si de algún modo se pudiera lograr disparar la búsqueda, luego invocar remotamente la funcionalidad de descargar el archivo resultante y aprovechando que ahora los archivos de planillas de cálculo .xlsx son un XML comprimido con Zip, sería tratar de aprovechar la funcionalidad "exportar Excel" para tomar los resultados de allí.

**Comment by pyro12** [comment]
Hola!

Extrano mucho esta addon.  He notado que los miembros registrados de subdivx.com pueden enviar mensajes a otros miembros incluidos el admin y los moderadores.

Me pregunto si alguien con el conocimiento para entender como implementar los cambios necesarios para que el addon funcione con la base de datos ha pedido su ayuda.

Este fue un addon fantastico y subdivx.com brinda un servicio maravilloso al recopilar y alojar tantos subtitulos. Quizas una especie de camaraderia sería la mejor manera de avanzar?

A veces, todo que necesitas hacer es a preguntar...

**Comment by ramiro** [comment]
Han habido avances y hay esperanzas para el addon.

Durante esta semana habrán novedades.

Voy a cerrar este ticket por ahora.
