### ISSUE TITLE
Por  el momento no funciona

### ISSUE THREAD

**Issue by Tribujos** [ramiro/service.subtitles.subdivx#55]
Hola como estas ahora no esta funcionando podrias arreglarlo y algo que queria saber si es posible hacerlo addon oara stremio seria buenísimo gracias por tu trabajo saludos

**Comment by ajrojasa** [comment]
Hola @ramiro @pedrochiuaua estuve jugando un poco con el codigo para correrlo en mi maquina y logre que trajera datos rescatando el json de la nueva pagina de subdivx

[test_addon.py.txt](https://github.com/user-attachments/files/16436716/test_addon.py.txt)


y tambien intente implementar los cambios en el archivo original zipeandolo e intentar instarlarlo en Kodi, pero la verdad no tengo experiencia empaquetando addons, pero supongo que deberia ser algo como:

[service.py.txt](https://github.com/user-attachments/files/16436718/service.py.txt)


Espero que esto pueda servir de algo para actualizar el addon para Kodi 21

Saludos,
Alonso.-

**Comment by ramiro** [comment]
Por favor ver discusión en  https://github.com/kodiar/kodiar.github.io/issues/1
