### ISSUE TITLE
addon stop working

### ISSUE THREAD

**Issue by juanredondo** [ramiro/service.subtitles.subdivx#9]
The addon is not working downloading subtitles.

**Comment by Sarcifi** [comment]
Hola Ramiro, muchas gracias por el addon, la version 0.0.8 solucionó el error de script en la version kodi 15.1 para Android Intel x86 en un nexus player, sin embargo al actualizar a 15.2 volvio el error, es posible que puedas revisar por favor, cuenta conmigo para la proporcionar logs

Gracias

**Comment by ramiro** [comment]
Guys, I'll need a lot more of information to be able to act on this.

I've just tried downloading subtitles for a new movie and it worked without problem.

Kodi versión is 15.2 (I suspect it was recently updated from the official kodi ppa repository) and my platform is Ubuntu Linux 14.04.

Please reopen this issue once you can detail movie names, attach logs, etc. to reproduce the problem.

Thanks!
